import {readFileSync,writeFileSync} from 'node:fs';
import {randomBytes,randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
import {setDefaultResultOrder} from 'node:dns';
import {runIntakeFrontendRegressions,stopIsolatedNext} from './browser-additions.mjs';
const require=createRequire('/app/package.json'),sharp=require('sharp'),{intakeReferenceFileId}=require('/phase3a/browser-helpers.cjs'),{createClient}=require('@supabase/supabase-js'),{chromium,expect}=require('@playwright/test');
setDefaultResultOrder('ipv4first');
const results=[],frontendEvidence=[],check=(value,code)=>{if(!value)throw new Error(code);};let server,browser,stage='preflight';
function classifyFailure(error){
 const codes=["ACTIVE_RELEASED_ONLY_AFTER_FAILED","ACTUAL_ACCEPTED_RESPONSE","ACTUAL_RATE_LIMIT_REACHED","ADDITIONAL_NEXT_READY","ASSERTION_FAILED","AUTH_FIXTURE","A_ATOMIC_EFFECTS","A_NOTICES_UNCHANGED","BROWSER_FAILED","B_RECEIPT_RELOAD","CHANGED_FILE_NO_POST","CLOSE","CLOSED_REPLAY","CORRECTED_ATOMIC_EFFECTS","CORRECTED_NEW_OPERATION","CORRECTED_NOTICE_SNAPSHOT","CSRF","DESTINATION_REJECTED","EFFECTS_READ","EPHEMERAL_REQUIRED","EXPECTED_REAL_SUBMISSIONS","EXPLICIT_CONFIRMED_RELEASES_ACTIVE","EXPLICIT_NEW_INTENT_SAME_ANSWERS_NEW_ID","FROZEN_OPERATION_REQUIRED","INTERRUPTION_NO_SERVER_EFFECTS","NEW_REQUEST_CHECKS_COMPLETED_CAPABILITY","NEXT_DID_NOT_EXIT","NEXT_EXITED_AFTER_READY","NEXT_PORT_NOT_CLOSED","NEXT_READY","NO_MOBILE_OVERFLOW","NO_SIDE_EFFECT","OLD_CLIENT","ONE_ATOMIC_INTAKE","ONLY_CORRECTED_REQUEST_EFFECTS","ONLY_TWO_NEW_REQUEST_EFFECTS","OP","OPERATION_READ","ORIGIN","ORIGINAL_FAILURE_PRESERVED","ORIGINAL_USER_LABELS","OWNER_NOTICES_READ","OWNER_PROJECTS_READ","PENDING_FIXTURE","REAL_COMMIT","RELOAD_NO_POST","REPLAY_NO_NOTICE","SAME_OPERATION_COMPLETES","SETTLED_CACHE","SWITCH_AUTHORITATIVE_FAILED_NO_EFFECTS","TOMBSTONE_NO_EFFECT","TWO_PROJECTS_EXACTLY_ONCE","VISIBLE_ORIGINAL_ANSWERS"];
 const message=typeof error?.message==='string'?error.message:'';
 const code=codes.includes(message)?message:'ASSERTION_FAILED';
 const kind=message.includes('strict mode violation')?'strict_locator':error?.name==='TimeoutError'||/\bTimeout\s+\d+ms\s+exceeded\b/i.test(message)?'timeout':error?.name==='AssertionError'||/^expect(?:\(|\.)/.test(message)||codes.includes(message)?'assertion':'other';
 const firstLabelLine=message.split(/\r?\n/).find(line=>line.includes('getByLabel('))??'';
 const expression=/getByLabel\(\s*(\/(?:\\.|[^\/\r\n])*\/[a-z]*|'(?:\\.|[^'\r\n])*'|"(?:\\.|[^"\r\n])*")/.exec(firstLabelLine)?.[1]??'';
 const label=expression.startsWith('/')?expression.slice(1,expression.lastIndexOf('/')).replace(/^\^|\$$/g,''):expression.slice(1,-1);
 const labels={'\u304a\u540d\u524d':'NAME','\u3054\u76f8\u8ac7\u30fb\u3054\u4f9d\u983c\u306e\u5185\u5bb9':'MESSAGE','\u3054\u4f9d\u983c\u306e\u8a73\u7d30':'MESSAGE','\u4fdd\u5b58\u3057\u305f\u5165\u529b\u5185\u5bb9':'SAVED_ANSWERS','\u5143\u306e\u4fdd\u5b58\u60c5\u5831':'RAW_ANSWERS','\u518d\u8a66\u884c\u7528\u306e\u753b\u50cf\u3092\u9078\u629e':'RETRY_FILE'};
 return {code,kind,locator:Object.hasOwn(labels,label)?labels[label]:'OTHER'};
}
async function test(name,fn){stage=name;try{await fn();results.push({name,status:'passed'});console.log(`PASS phase3a-browser/${name}`);}catch(e){results.push({name,status:'failed',...classifyFailure(e)});console.log(`FAIL phase3a-browser/${name}`);}persist();}
function persist(){writeFileSync('/results/phase3a-browser.json',JSON.stringify({tests:results,frontendEvidence,passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed').length,skipped:0,engine:'Chromium mobile390px; real ephemeral Next/DB/Storage; not iPhone Safari; sending disabled'},null,2));}
async function main(){
 check(process.env.PHASE_N_BROWSER==='ephemeral','EPHEMERAL_REQUIRED');const {origin}=JSON.parse(readFileSync('/runtime/network.json','utf8'));check(/^http:\/\/172\.30\.250\.\d+:8000$/.test(origin),'DESTINATION_REJECTED');const keys=JSON.parse(readFileSync('/runtime/credentials.json','utf8'));
 const admin=createClient(origin,keys.service,{auth:{persistSession:false,autoRefreshToken:false}}),password=randomBytes(32).toString('hex');
 const auth=await admin.auth.admin.createUser({email:'phase3a-owner@phase0b-browser.invalid',password,email_confirm:true});check(!auth.error&&auth.data.user,'AUTH_FIXTURE');const owner=auth.data.user.id;
 // Admission contents are the actual published defaults plus explicit fixture flags; only this ephemeral DB is changed.
 const app='http://localhost:3000';const startNext=()=>spawn(process.execPath,['/app/node_modules/next/dist/bin/next','dev','--hostname','localhost','--port','3000'],{cwd:'/app',env:{PATH:'/runtime-bin:/usr/local/bin:/usr/bin:/bin',HOME:'/tmp',TMPDIR:'/tmp',NODE_ENV:'development',NEXT_TELEMETRY_DISABLED:'1',NODE_OPTIONS:'--dns-result-order=ipv4first',PHASE_N_BROWSER:'ephemeral',PHASE_0B_BROWSER:'ephemeral',PHASE_3A_BROWSER:'ephemeral',NEXT_PUBLIC_SUPABASE_URL:origin,NEXT_PUBLIC_SUPABASE_ANON_KEY:keys.anon,SUPABASE_SERVICE_ROLE_KEY:keys.service,NATORI_OWNER_USER_ID:owner,NEXT_PUBLIC_SITE_URL:app,NATORI_PUBLIC_INTAKE_V2:'1',NATORI_ACCEPTANCE_OUTBOX_ENABLED:'1',NATORI_NOTIFICATION_SENDING_ENABLED:'0',RESEND_API_KEY:'',NATORI_ORDER_MAIL_FROM:'Fixture <sender@phase3a.invalid>',NATORI_PORTFOLIO_CONTACT_TO:'artist@phase3a.invalid'},stdio:['ignore','pipe','pipe']});
 server=startNext();
 const compileErrors=new Set();for(const stream of[server.stdout,server.stderr])stream.on('data',b=>{for(const code of ['Module not found','Failed to compile','SyntaxError','EADDRINUSE'])if(b.toString().includes(code))compileErrors.add(code);});
 let ready=false;const deadline=Date.now()+120000;while(Date.now()<deadline&&server.exitCode===null){try{const r=await fetch(app+'/ja/fixture-session',{signal:AbortSignal.timeout(2000)});if(r.ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,400));}check(ready,'NEXT_READY');
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();await context.route('**/*',r=>new URL(r.request().url()).origin===app?r.continue():r.abort('blockedbyclient'));
 const endpoint=app+'/api/natori/portfolio/contact',url=app+'/ja/fixture-intake/structured',key='natori-intake-operation-v1';
 async function newForm(mode='structured'){await page.goto(app+'/ja/fixture-intake/'+mode);await page.evaluate(k=>{for(const item of [k,'natori-intake-original-answers-v1','natori-intake-receipts-v1'])sessionStorage.removeItem(item);},key);await page.reload();await expect(page.getByLabel(/お名前/)).toBeEnabled();}
 async function fill(message='Synthetic browser request'){await page.getByLabel(/お名前/).fill('Synthetic browser');await page.getByLabel(/メールアドレス/).fill('client@phase3a.invalid');await page.getByLabel(/ご相談・ご依頼の内容/).fill(message);await page.getByRole('button',{name:'内容を確認する'}).click();}
 async function count(id){const op=(await admin.from('natori_intake_operations').select('project_id,status').eq('owner_id',owner).eq('operation_id',id).single()).data;check(op,'OP');const projects=(await admin.from('natori_projects').select('id').eq('id',op.project_id)).data??[],notices=(await admin.from('natori_notification_jobs').select('id').eq('project_id',op.project_id)).data??[];return {op,projects,notices};}
 let first;
 await test('actual-submit-commit-ack-loss-freezes-and-reload-recovers-one-receipt',async()=>{
  await newForm();await fill('Lost acknowledgement');let resolve;const intercepted=new Promise(r=>{resolve=r;});let interceptionError;
  await page.route('**/api/natori/portfolio/contact',async r=>{if(!r.request().headers()['content-type']?.startsWith('multipart/'))return r.continue();try{const response=await r.fetch(),data=await response.json();check(response.status()===200&&data.accepted,'REAL_COMMIT');first=data.receipt;await r.abort('failed');}catch(e){interceptionError=e;await r.abort('failed').catch(()=>{});}finally{resolve();}});
  await page.getByRole('button',{name:'相談内容を送信する'}).click();await intercepted;if(interceptionError)throw interceptionError;await expect(page.getByLabel(/お名前/)).toBeDisabled();await expect(page.getByRole('button',{name:'受付結果を確認する'})).toBeEnabled();await page.unroute('**/api/natori/portfolio/contact');
  let multipart=0;page.on('request',r=>{if(r.url()===endpoint&&r.headers()['content-type']?.startsWith('multipart/'))multipart++;});await page.reload();await expect(page.getByText('送信ありがとうございます!',{exact:true})).toBeVisible();await expect(page.getByText(first,{exact:false})).toBeVisible();check(multipart===0,'RELOAD_NO_POST');const e=await count(first);check(e.projects.length===1&&e.notices.length===2,'ONE_ATOMIC_INTAKE');
 });
 await test('same-completed-capability-replays-after-server-admission-closes',async()=>{
  const saved=await page.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),key);const old=(await admin.from('natori_portfolio_content').select('content').eq('id','main').maybeSingle()).data;
  const content=old?.content??{commissionOpen:true,massProductionIllustrationOpen:true};check(!(await admin.from('natori_portfolio_content').upsert({id:'main',content:{...content,commissionOpen:false,massProductionIllustrationOpen:false}})).error,'CLOSE');try{const response=await context.request.post(endpoint,{data:{action:'reconcile',operationId:saved.operationId,requestHash:saved.requestHash},headers:{'x-requested-with':'me-ish'}});check(response.status()===200&&(await response.json()).receipt===first,'CLOSED_REPLAY');await page.reload();await expect(page.getByText('送信ありがとうございます!',{exact:true})).toBeVisible();check((await count(first)).notices.length===2,'REPLAY_NO_NOTICE');}finally{await admin.from('natori_portfolio_content').upsert({id:'main',content:{...content,commissionOpen:true,massProductionIllustrationOpen:true}});}
 });
 await test('interrupted-before-begin-reload-fences-delayed-request-and-restores-answers',async()=>{
  await newForm();await fill('Keep this exact draft');let resolve;const aborted=new Promise(r=>{resolve=r;});await page.route('**/api/natori/portfolio/contact',async r=>{if(r.request().headers()['content-type']?.startsWith('multipart/')){await r.abort('failed');resolve();}else await r.continue();});
  await page.getByRole('button',{name:'相談内容を送信する'}).click();await aborted;await expect(page.getByRole('button',{name:'受付結果を確認する'})).toBeEnabled();const saved=await page.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),key);await page.unroute('**/api/natori/portfolio/contact');await page.reload();await expect(page.getByLabel(/お名前/)).toBeEnabled();await expect(page.getByLabel(/ご相談・ご依頼の内容/)).toHaveValue('Keep this exact draft');check(await page.evaluate(k=>sessionStorage.getItem(k),key)===null,'SETTLED_CACHE');const e=await count(saved.operationId);check(e.op.status==='failed'&&e.projects.length===0&&e.notices.length===0,'TOMBSTONE_NO_EFFECT');
 });
 await test('reload-pending-image-reselection-validates-original-bytes-before-same-id-retry',async()=>{
  await newForm();await page.getByLabel(/お名前/).fill('Synthetic browser');await page.getByLabel(/メールアドレス/).fill('client@phase3a.invalid');await page.getByLabel(/ご相談・ご依頼の内容/).fill('Image pending original');
  const png=await sharp({create:{width:3,height:2,channels:4,background:'#ec4899'}}).png().toBuffer();
  await page.locator('input[type=file]').setInputFiles({name:'original.png',mimeType:'image/png',buffer:png});await page.getByRole('button',{name:'内容を確認する'}).click();
  let resolve;const abort=new Promise(r=>{resolve=r;});await page.route('**/api/natori/portfolio/contact',async r=>{if(r.request().headers()['content-type']?.startsWith('multipart/')){await r.abort('failed');resolve();}else await r.continue();});
  await page.getByRole('button',{name:'相談内容を送信する'}).click();await abort;await expect(page.getByRole('button',{name:'受付結果を確認する'})).toBeEnabled();const saved=await page.evaluate(k=>JSON.parse(sessionStorage.getItem(k)),key);
  check(!(await admin.rpc('natori_intake_begin_v1',{p_owner_id:owner,p_operation_id:saved.operationId,p_request_hash:saved.requestHash,p_manifest:saved.manifest,p_file_ids:saved.manifest.map((file,index)=>intakeReferenceFileId(saved.operationId,index,file.digest)),p_claim_token:randomUUID(),p_mass_production:false})).error,'PENDING_FIXTURE');
  await page.unroute('**/api/natori/portfolio/contact');await page.reload();await expect(page.getByRole('button',{name:'同じ内容で再試行する'})).toBeEnabled();await expect(page.getByLabel(/お名前/)).toBeDisabled();
  const mismatch=await sharp({create:{width:3,height:2,channels:4,background:'#000000'}}).png().toBuffer();await page.getByLabel('再試行用の画像を選択').setInputFiles({name:'changed.png',mimeType:'image/png',buffer:mismatch});let posts=0;const observe=r=>{if(r.url()===endpoint&&r.headers()['content-type']?.startsWith('multipart/'))posts++;};page.on('request',observe);
  await page.getByRole('button',{name:'同じ内容で再試行する'}).click();await expect(page.getByText('前回と同じ画像を、同じ順番で選択してください。異なる画像では再試行しません。')).toBeVisible();check(posts===0,'CHANGED_FILE_NO_POST');
  await page.getByLabel('再試行用の画像を選択').setInputFiles({name:'renamed.png',mimeType:'image/png',buffer:png});await admin.from('natori_intake_operations').update({lease_expires_at:new Date(Date.now()-1000).toISOString()}).eq('owner_id',owner).eq('operation_id',saved.operationId);
  await page.getByRole('button',{name:'同じ内容で再試行する'}).click();await expect(page.getByText('送信ありがとうございます!',{exact:true})).toBeVisible();const e=await count(saved.operationId);check(e.projects.length===1&&e.notices.length===2&&posts===1,'SAME_OPERATION_COMPLETES');page.off('request',observe);
 });
 await test('old-client-no-id-and-real-csrf-origin-boundaries-reject-before-sideeffects',async()=>{
  const before=(await admin.from('natori_intake_operations').select('operation_id').eq('owner_id',owner)).data?.length??0;
  const old={name:'Old synthetic',email:'client@phase3a.invalid',requestType:'旧相談',details:'Old draft'};
  check((await context.request.post(endpoint,{data:old,headers:{'x-requested-with':'me-ish'}})).status()===409,'OLD_CLIENT');check((await context.request.post(endpoint,{data:old})).status()===403,'CSRF');check((await context.request.post(endpoint,{data:old,headers:{'x-requested-with':'me-ish','origin':'https://attacker.invalid'}})).status()===403,'ORIGIN');check(((await admin.from('natori_intake_operations').select('operation_id').eq('owner_id',owner)).data?.length??0)===before,'NO_SIDE_EFFECT');
 });
 await test('mobile-pending-controls-and-completed-confirmation-do-not-overflow',async()=>{
  await newForm();await fill('Mobile pending');await page.route('**/api/natori/portfolio/contact',r=>r.abort('failed'));await page.getByRole('button',{name:'相談内容を送信する'}).click();await expect(page.getByRole('button',{name:'受付結果を確認する'})).toBeEnabled();check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'NO_MOBILE_OVERFLOW');await page.unroute('**/api/natori/portfolio/contact');
 });
 await context.close();await stopIsolatedNext(server,app,check);server=undefined;
 await runIntakeFrontendRegressions({test,check,expect,browser,app,endpoint,owner,admin,key,startNext,compileErrors,onEvidence:evidence=>{frontendEvidence.push(evidence);persist();}});
 persist();check(results.length===9&&results.every(t=>t.status==='passed')&&compileErrors.size===0,'BROWSER_FAILED');
}
main().catch(()=>{console.error(`Phase3A browser failed at ${stage}; raw logs withheld`);process.exitCode=1;}).finally(async()=>{await browser?.close();if(server?.exitCode===null){server.kill('SIGTERM');await Promise.race([new Promise(r=>server.once('exit',r)),new Promise(r=>setTimeout(()=>{server.kill('SIGKILL');r();},5000))]);}});
