import {createClient} from '@supabase/supabase-js';
import {readFileSync,writeFileSync} from 'node:fs';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import sharp from 'sharp';
import {spawn} from 'node:child_process';
const check=(value:unknown,code:string)=>{if(!value)throw new Error(code);};
const results:{name:string;status:string;code?:string}[]=[];
async function test(name:string,fn:()=>Promise<void>){try{await fn();results.push({name,status:'passed'});console.log(`PASS phase3a/${name}`);}catch(e){const code=e instanceof Error&&/^[A-Z_0-9]+$/.test(e.message)?e.message:'ASSERTION_FAILED';results.push({name,status:'failed',code});console.log(`FAIL phase3a/${name} ${code}`);}}
async function main(){
 const {origin}=JSON.parse(readFileSync('/runtime/network.json','utf8'));check(/^http:\/\/172\.30\.250\.\d+:8000$/.test(origin),'DESTINATION_REJECTED');
 const keys=JSON.parse(readFileSync('/runtime/credentials.json','utf8'));
 const db=createClient(origin,keys.service,{auth:{persistSession:false}}),peer=createClient(origin,keys.service,{auth:{persistSession:false}});
 const direct=globalThis.fetch;let fault:'finish'|'upload'|'hold_upload'|'remove'|null=null,blocked=0;
 let observeUpload:()=>void=()=>{},releaseUpload:()=>void=()=>{},uploadRelease:Promise<void>=Promise.resolve();
 globalThis.fetch=async(input,init)=>{const u=new URL(typeof input==='string'?input:input instanceof URL?input.href:input.url);if(u.origin!==origin){blocked++;throw new Error('DESTINATION_REJECTED');}
  if(fault==='hold_upload'&&u.pathname.includes('/storage/v1/object/natori-inquiry-refs/')){fault=null;observeUpload();await uploadRelease;}
  if(fault==='remove'&&u.pathname.includes('/storage/v1/object/natori-inquiry-refs')&&(init?.method??(input instanceof Request?input.method:'GET')).toUpperCase()==='DELETE'){fault=null;return new Response('{}',{status:503});}
  const response=await direct(input,init);if(fault==='finish'&&u.pathname.endsWith('/rpc/natori_intake_finish_v1')){fault=null;check(response.ok,'COMMITTED');return new Response('{}',{status:503});}
  if(fault==='upload'&&u.pathname.includes('/storage/v1/object/natori-inquiry-refs/')){fault=null;check(response.ok,'UPLOADED');return new Response('{}',{status:503});}return response;};
 try{
  const auth=await db.auth.admin.createUser({email:'owner@phase3a.invalid',password:randomBytes(32).toString('hex'),email_confirm:true});check(auth.data.user,'AUTH_FIXTURE');const owner=auth.data.user!.id;
  Object.assign(process.env,{NEXT_PUBLIC_SUPABASE_URL:origin,NEXT_PUBLIC_SUPABASE_ANON_KEY:keys.anon,SUPABASE_SERVICE_ROLE_KEY:keys.service,NATORI_OWNER_USER_ID:owner,NATORI_PUBLIC_INTAKE_V2:'1',NATORI_ACCEPTANCE_OUTBOX_ENABLED:'1',NATORI_NOTIFICATION_SENDING_ENABLED:'0',RESEND_API_KEY:'',ADMIN_API_TOKEN:'',NEXT_PUBLIC_SITE_URL:'http://localhost'});
  const service=await import('../../src/features/natori/server/publicIntakeOperationService');
  const route=await import('../../src/app/api/natori/portfolio/contact/route');
  const {canonicalizeIntake}=await import('../../src/features/natori/lib/intakeOperation');
  const {buildNatoriRequestDataV1,createInitialPortfolioRequestFormState}=await import('../../src/features/natori/lib/portfolioRequestForm');
  const {defaultPortfolioContent}=await import('../../src/features/natori/constants/portfolioContent');
  const saved={...defaultPortfolioContent,commissionOpen:true,massProductionIllustrationOpen:true};
  async function availability(commissionOpen=true,massProductionIllustrationOpen=true){check(!(await db.from('natori_portfolio_content').upsert({id:'main',content:{...saved,commissionOpen,massProductionIllustrationOpen}})).error,'CONTENT');}
  await availability();
  const fields=()=>({name:'Synthetic',email:'client@phase3a.invalid',formVersion:'etorie-request-v1',requestData:JSON.stringify(buildNatoriRequestDataV1({...createInitialPortfolioRequestFormState(),message:'Synthetic request',publicationPolicy:'unknown'},[])),referenceLinks:JSON.stringify([{url:'https://example.invalid/reference#fragment',label:'Reference'}])});
  const canonical=()=>canonicalizeIntake(fields(),[]);
  type Canonical=ReturnType<typeof canonical>;
  async function op(id:string){const row=await db.from('natori_intake_operations').select('*').eq('owner_id',owner).eq('operation_id',id).single();check(!row.error&&row.data,'OP');return row.data!;}
  async function effects(id:string){const row=await op(id),project=(await db.from('natori_projects').select('*').eq('id',row.project_id)).data??[];
   const notices=(await db.from('natori_notification_jobs').select('id,purpose,snapshot').eq('project_id',row.project_id)).data??[];
   const tasks=(await db.from('natori_project_tasks').select('id').eq('project_id',row.project_id)).data??[];
   const refs=(await db.from('natori_inquiry_reference_files').select('storage_path').eq('project_id',row.project_id)).data??[];
   const links=(await db.from('natori_project_reference_links').select('*').eq('project_id',row.project_id)).data??[];return {row,project,notices,tasks,refs,links};}
  async function begin(id:string,c:Canonical=canonical(),token=randomUUID(),mass=false){const hash=service.hashCanonicalIntake(c),r=await db.rpc('natori_intake_begin_v1',{p_owner_id:owner,p_operation_id:id,p_request_hash:hash,p_manifest:c.manifest,p_file_ids:c.manifest.map((m,index)=>service.intakeReferenceFileId(id,index,m.digest)),p_claim_token:token,p_mass_production:mass});check(!r.error&&r.data?.[0],'BEGIN');return {hash,token,row:r.data![0]};}
  async function finish(id:string,hash:string,token:string,c:Canonical=canonical(),mass=false){return db.rpc('natori_intake_finish_v1',{p_owner_id:owner,p_operation_id:id,p_request_hash:hash,p_claim_token:token,p_client_name:c.submission.clientName,p_client_email:c.submission.clientEmail,p_request_data:c.submission.requestData,p_reference_links:c.referenceLinks,p_mass_production:mass});}
  async function post(id:string,c:Canonical=canonical(),ip:string=randomUUID(),csrf=true){const f=fields(),body=new FormData();for(const[k,v]of Object.entries(f))body.set(k,v);body.set('operationId',id);body.set('requestHash',service.hashCanonicalIntake(c));return route.POST(new Request('http://localhost/api/natori/portfolio/contact',{method:'POST',body,headers:{'x-forwarded-for':ip,...(csrf?{'x-requested-with':'me-ish'}:{})}}));}
  async function hold(id:string,content:boolean|null=false){const active=Promise.resolve(peer.rpc('phase3a_hold_v1',{p_owner:owner,p_operation:id,p_content:content,p_seconds:2}));let acquired=false;
   for(let n=0;n<100;n++){const probe=await db.rpc('phase3a_is_held_v1',{p_operation:id});check(!probe.error,'PROBE');if(probe.data){acquired=true;break;}await new Promise(r=>setTimeout(r,10));}check(acquired,'LOCK_ACQUIRED');return {active};}

  async function lateWaitRollback(stage:'owner_fk'|'project_relation'|'notification_relation'|'completion_update'){
   const id=randomUUID(),c=canonical(),b=await begin(id,c);
   const active=Promise.resolve(peer.rpc('phase3a_hold_late_v1',{p_owner:owner,p_operation:id,p_stage:stage,p_seconds:4}));
   let acquired=false;
   for(let n=0;n<100;n++){const probe=await db.rpc('phase3a_is_held_v1',{p_operation:id});check(!probe.error,'LATE_PROBE');if(probe.data){acquired=true;break;}await new Promise(r=>setTimeout(r,10));}
   check(acquired,'LATE_LOCK_ACQUIRED');
   const expiry=new Date(Date.now()+1500).toISOString();
   check(!(await db.from('natori_intake_operations').update({lease_expires_at:expiry}).eq('owner_id',owner).eq('operation_id',id)).error,'LATE_SHORT_LEASE');
   const waiting=Promise.resolve(finish(id,b.hash,b.token,c));let blocked=false;
   for(let n=0;n<100;n++){const probe=await db.rpc('phase3a_finish_is_waiting_v1',{p_operation:id});check(!probe.error,'LATE_WAIT_PROBE');if(probe.data){blocked=true;break;}await new Promise(r=>setTimeout(r,10));}
   check(blocked&&Date.now()<Date.parse(expiry),'ACTUAL_FINISH_BLOCKED_BEFORE_EXPIRY');
   check(!(await active).error,'LATE_HOLD_DONE');
   const result=await waiting;check(result.error?.code==='40001','LATE_EXPIRED_CLAIM_ROLLBACK');
   const before=await effects(id);
   check(before.project.length===0&&before.notices.length===0&&before.tasks.length===0&&before.refs.length===0&&before.links.length===0,'LATE_NO_PARTIAL_EFFECTS');
   check(before.row.status==='processing'&&before.row.claim_token===b.token&&before.row.replay_result===null&&before.row.notification_ids.length===0,'LATE_ORIGINAL_OPERATION_RESTORED');
   check((await service.lookupPublicIntakeOperation(id,b.hash)).kind==='processing','LATE_UNKNOWN_REMAINS_FROZEN');
   check((await service.submitPublicIntakeOperation(id,c,[])).kind==='completed','LATE_SAME_OPERATION_RECOVERY');
   const after=await effects(id);check(after.row.project_id===before.row.project_id&&after.project.length===1&&after.notices.length===2,'LATE_ONE_PROJECT_NOTICE_PAIR');
   const keys=(await db.from('natori_notification_jobs').select('notification_key').eq('project_id',after.row.project_id)).data??[];
   check(keys.map(row=>row.notification_key).sort().join(',')===['intake/'+owner+'/'+id+'/intake_artist','intake/'+owner+'/'+id+'/intake_client'].sort().join(','),'LATE_EXACT_ORIGINAL_NOTICE_KEYS');
  }

  async function killAtBoundary(id:string,mode:'begin'|'upload'|'finish',c:Canonical=canonical(),files:{bytes:string;name:string;type:string}[]=[]){
   const child=spawn(process.execPath,['/phase3a/claim-worker.cjs',owner,mode],{env:{NODE_ENV:'test',PATH:process.env.PATH,NODE_PATH:process.env.NODE_PATH},stdio:['pipe','pipe','ignore']});
   const exit=new Promise<NodeJS.Signals|null>(resolve=>child.once('exit',(_code,signal)=>resolve(signal)));
   try{await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('WORKER_TIMEOUT')),15000);let text='';child.on('error',()=>{clearTimeout(timer);reject(new Error('WORKER_START'));});child.stdout.on('data',data=>{text+=String(data);if(text.includes('BOUNDARY_REACHED')){clearTimeout(timer);resolve();}if(text.includes('HELPER_FAILED')){clearTimeout(timer);reject(new Error('WORKER_BOUNDARY'));}});child.stdin.end(JSON.stringify({operationId:id,canonical:c,files}));});child.kill('SIGKILL');check((await exit)==='SIGKILL','ACTUALLY_KILLED');}
   finally{if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');}
  }
  await test('structured-original-answers-links-zero-tasks-and-two-notices-atomic',async()=>{const id=randomUUID(),c=canonical();check((await service.submitPublicIntakeOperation(id,c,[])).kind==='completed','COMPLETED');const e=await effects(id);check(e.project.length===1&&e.tasks.length===0&&e.notices.length===2&&e.links.length===1,'ATOMIC_COUNTS');check(e.project[0].type==='undecided'&&e.project[0].amount===null&&e.project[0].request_data.message===c.submission.requestData.message&&e.project[0].request_data.formVersion==='etorie-request-v1','ORIGINAL_REQUEST');check(e.links[0].url==='https://example.invalid/reference'&&e.notices.map(n=>n.purpose).sort().join(',')==='intake_artist,intake_client','EXACT_LINK_NOTICES');});
  await test('concurrent-identical-operation-only-one-project-and-two-intents',async()=>{const id=randomUUID(),c=canonical(),r=await Promise.all([service.submitPublicIntakeOperation(id,c,[]),service.submitPublicIntakeOperation(id,c,[])]);check(r.some(x=>x.kind==='completed'),'ONE_COMPLETES');const e=await effects(id);check(e.project.length===1&&e.notices.length===2,'ONE_EFFECT');check((await service.submitPublicIntakeOperation(id,c,[])).kind==='completed','REPLAY');});
  await test('changed-hash-conflicts-and-new-id-same-content-is-new-intake',async()=>{const id=randomUUID(),c=canonical();await service.submitPublicIntakeOperation(id,c,[]);const changed={...c,submission:{...c.submission,clientName:'Changed'}};check((await service.submitPublicIntakeOperation(id,changed,[])).kind==='conflict','CONFLICT');const next=randomUUID();check((await service.submitPublicIntakeOperation(next,c,[])).kind==='completed','NEW_ID');check((await op(id)).project_id!==(await op(next)).project_id,'SEPARATE_PROJECT');});
  await test('completed-replays-after-admission-closure-and-project-advancement',async()=>{const id=randomUUID(),c=canonical();const first=await service.submitPublicIntakeOperation(id,c,[]),e=await effects(id);await db.from('natori_projects').update({status:'closed',next_action:'Keep terminal',deleted_at:new Date().toISOString()}).eq('id',e.row.project_id);await availability(false,false);process.env.NATORI_PUBLIC_INTAKE_V2='0';try{const response=await post(id,c);check(response.status===200,'CLOSED_REPLAY');const body=await response.json();check(body.receipt===id&&body.accepted===true&&!JSON.stringify(body).includes('client@')&&!JSON.stringify(body).includes(e.row.project_id),'MINIMAL_RECEIPT');check((await service.submitPublicIntakeOperation(id,c,[])).kind===first.kind,'SAME_RESULT');check((await effects(id)).notices.length===2,'NO_NEW_NOTICE');}finally{process.env.NATORI_PUBLIC_INTAKE_V2='1';await availability();}});
  await test('ordinary-quota-replay-exemption-remains-separately-abuse-limited',async()=>{const ip='phase3a-quota',c=canonical(),ids=[randomUUID(),randomUUID(),randomUUID()];for(const id of ids)check((await post(id,c,ip)).status===200,'FIRST_QUOTA');check((await post(randomUUID(),c,ip)).status===429,'QUOTA');check((await post(ids[0],c,ip)).status===200,'QUOTA_REPLAY');const abuse='phase3a-abuse';let last=0;for(let n=0;n<61;n++)last=(await post(ids[0],c,abuse)).status;check(last===429,'ABUSE_REPLAY_BOUND');});
  await test('legacy-json-lossless-labels-shares-atomic-save-path',async()=>{const legacy={name:'Legacy synthetic',email:'client@phase3a.invalid',requestType:'立ち絵の旧ラベル',message:'Legacy message',details:'D'.repeat(3000),budget:'相談',deadline:'未定',usage:'旧用途',style:'旧スタイル',commercial:'相談',options:['旧オプション'],user_id:randomUUID(),referenceImages:['https://ignored.invalid/image']};const c=canonicalizeIntake(legacy,[]),id=randomUUID();const response=await route.POST(new Request('http://localhost/api/natori/portfolio/contact',{method:'POST',headers:{'content-type':'application/json','x-requested-with':'me-ish','x-forwarded-for':randomUUID()},body:JSON.stringify({...legacy,operationId:id,requestHash:service.hashCanonicalIntake(c)})}));check(response.status===200,'LEGACY_ACK');const e=await effects(id);check(e.project[0].user_id===owner&&e.project[0].request_data.legacySource.details==='D'.repeat(3000)&&e.tasks.length===0&&e.refs.length===0&&e.notices.length===2,'LOSSLESS_LEGACY');});
  await test('storage-real-bytes-stable-path-duplicate-and-upload-response-loss',async()=>{const png=await sharp({create:{width:4,height:3,channels:4,background:'#ec4899'}}).png().toBuffer(),file=new File([png],'ref.png',{type:'image/png'}),id=randomUUID(),c=canonical();c.manifest=[{digest:createHash('sha256').update(png).digest('hex'),size:png.length,type:'image/png'}];fault='upload';check((await service.submitPublicIntakeOperation(id,c,[file])).kind==='completed','UPLOAD_LOSS_RECOVERED');const e=await effects(id);check(e.refs.length===1&&e.refs[0].storage_path===e.row.reference_paths[0],'STABLE_REF');check((await service.submitPublicIntakeOperation(id,c,[file])).kind==='completed'&&(await effects(id)).refs.length===1,'NO_DUPLICATE_REF');});
  await test('actual-worker-kill-after-begin-expiry-reuses-one-project-id',async()=>{const id=randomUUID();await killAtBoundary(id,'begin');const before=await effects(id);check(before.project.length===0&&before.notices.length===0&&before.row.status==='processing','KILLED_NO_EFFECT');await db.from('natori_intake_operations').update({lease_expires_at:new Date(Date.now()-1000).toISOString()}).eq('owner_id',owner).eq('operation_id',id);check((await service.submitPublicIntakeOperation(id,canonical(),[])).kind==='completed','KILLED_RECOVERED');const after=await effects(id);check(after.row.project_id===before.row.project_id&&after.project.length===1&&after.notices.length===2,'STABLE_PROJECT_AFTER_KILL');});
  await test('actual-worker-kill-mid-upload-reuses-exact-object-and-attachment-link',async()=>{const png=await sharp({create:{width:3,height:2,channels:4,background:'#ffccdd'}}).png().toBuffer(),id=randomUUID(),c=canonical();c.manifest=[{digest:createHash('sha256').update(png).digest('hex'),size:png.length,type:'image/png'}];await killAtBoundary(id,'upload',c,[{bytes:png.toString('base64'),name:'original.png',type:'image/png'}]);const before=await effects(id);check(before.project.length===0&&before.refs.length===0&&before.notices.length===0,'UPLOADED_NOT_SHARED');check(!(await db.storage.from('natori-inquiry-refs').download(before.row.reference_paths[0])).error,'EXACT_OBJECT_EXISTS');await db.from('natori_intake_operations').update({lease_expires_at:new Date(Date.now()-1000).toISOString()}).eq('owner_id',owner).eq('operation_id',id);check((await service.submitPublicIntakeOperation(id,c,[new File([png],'renamed.png',{type:'image/png'})])).kind==='completed','UPLOAD_KILL_RECOVERED');const after=await effects(id);check(after.row.project_id===before.row.project_id&&after.refs.length===1&&after.refs[0].storage_path===before.row.reference_paths[0]&&after.notices.length===2,'ONE_STABLE_OBJECT_LINK');});
  await test('actual-worker-kill-after-commit-before-ack-replays-original-receipt',async()=>{const id=randomUUID();await killAtBoundary(id,'finish');const before=await effects(id);check(before.row.status==='completed'&&before.project.length===1&&before.notices.length===2,'COMMITTED_BEFORE_KILL');const response=await post(id);check(response.status===200&&(await response.json()).receipt===id,'KILLED_COMMIT_REPLAY');const after=await effects(id);check(after.row.project_id===before.row.project_id&&after.notices.length===2,'NO_DUPLICATE_AFTER_KILL');});
  await test('finish-response-loss-reconciles-durable-commit',async()=>{const id=randomUUID();fault='finish';check((await service.submitPublicIntakeOperation(id,canonical(),[])).kind==='completed','ACK_LOSS_RECONCILED');check((await effects(id)).notices.length===2,'ONE_PAIR');});
  await test('finish-validation-error-rolls-back-entire-project-and-notice-transaction',async()=>{const id=randomUUID(),c=canonical(),b=await begin(id,c);const invalid={...c,submission:{...c.submission,requestData:{...c.submission.requestData,schemaVersion:2}}} as unknown as Canonical;check((await finish(id,b.hash,b.token,invalid)).error,'VALIDATION_REJECTED');const e=await effects(id);check(e.project.length===0&&e.notices.length===0&&e.refs.length===0&&e.links.length===0&&e.row.status==='processing','NO_PARTIAL_STATE');});
  await test('expired-claim-is-fenced-and-exact-tombstone-blocks-delayed-original',async()=>{const id=randomUUID(),c=canonical(),a=await begin(id,c);await db.from('natori_intake_operations').update({lease_expires_at:new Date(Date.now()-1000).toISOString()}).eq('owner_id',owner).eq('operation_id',id);const b=await begin(id,c);check((await finish(id,a.hash,a.token,c)).data?.[0]?.result==='busy','STALE_FENCED');check((await finish(id,b.hash,b.token,c)).data?.[0]?.result==='completed','NEW_CLAIM');const delayed=randomUUID(),hash=service.hashCanonicalIntake(c);check((await service.settlePublicIntakeOperation(delayed,hash)).kind==='failed','ABSENT_TOMBSTONE');check((await begin(delayed,c)).row.result==='failed','DELAYED_BEGIN_FENCED');check((await effects(delayed)).project.length===0,'NO_DELAYED_PROJECT');});
  await test('closed-new-operation-is-durably-failed-after-reopening',async()=>{const id=randomUUID(),c=canonical();await availability(false,false);check((await begin(id,c)).row.result==='failed','CLOSED_FAILED');await availability();check((await begin(id,c)).row.result==='failed'&&(await effects(id)).project.length===0,'REOPEN_NO_RESURRECTION');});
  await test('missing-mass-setting-fails-closed-while-normal-default-is-preserved',async()=>{check(!(await db.from('natori_portfolio_content').update({content:{commissionOpen:true}}).eq('id','main')).error,'MISSING_MASS_CONTENT');const id=randomUUID();check((await begin(id,canonical(),randomUUID(),true)).row.result==='failed','MASS_FAIL_CLOSED');check((await begin(randomUUID())).row.result==='claimed','NORMAL_DEFAULT');await availability();});
  await test('begin-clock-after-operation-lock-wait-issues-live-lease',async()=>{const id=randomUUID(),h=await hold(id),waiting=begin(id);check(!(await h.active).error,'HOLD_DONE');const b=await waiting;check(b.row.result==='claimed','CLAIMED');const row=await op(id);check(Date.parse(row.lease_expires_at)-Date.now()>118000,'POST_LOCK_LEASE');});
  await test('renewal-expiring-during-operation-row-lock-wait-cannot-resurrect-lease',async()=>{const id=randomUUID(),b=await begin(id),exp=new Date(Date.now()+1000).toISOString();check(!(await db.from('natori_intake_operations').update({lease_expires_at:exp}).eq('owner_id',owner).eq('operation_id',id)).error,'SHORT_LEASE');const h=await hold(id,null);check(Date.now()<Date.parse(exp),'PRE_RENEW_EXPIRY');const waiting=Promise.resolve(db.rpc('natori_intake_touch_v1',{p_owner_id:owner,p_operation_id:id,p_request_hash:b.hash,p_claim_token:b.token}));check(!(await h.active).error,'ROW_HOLD_DONE');check((await waiting).data===false,'POST_ROW_LOCK_CLOCK');check(Date.parse((await op(id)).lease_expires_at)===Date.parse(exp),'NO_LEASE_RESURRECTION');});
  await test('finish-lease-expiring-during-content-lock-wait-cannot-create-project',async()=>{const id=randomUUID(),c=canonical(),b=await begin(id,c),exp=new Date(Date.now()+1000).toISOString();check(!(await db.from('natori_intake_operations').update({lease_expires_at:exp}).eq('owner_id',owner).eq('operation_id',id)).error,'SHORT_LEASE');const h=await hold(id,true);check(Date.now()<Date.parse(exp),'PRE_EXPIRY');const waiting=Promise.resolve(finish(id,b.hash,b.token,c));check(!(await h.active).error,'CONTENT_HOLD_DONE');check((await waiting).data?.[0]?.result==='busy','POST_CONTENT_LOCK_FENCE');const e=await effects(id);check(e.project.length===0&&e.notices.length===0,'NO_EXPIRED_COMMIT');});
  await test('finish-lease-expiring-during-owner-foreign-key-wait-rolls-back-all-effects',async()=>lateWaitRollback('owner_fk'));
  await test('finish-lease-expiring-during-project-relation-wait-rolls-back-all-effects',async()=>lateWaitRollback('project_relation'));
  await test('finish-lease-expiring-during-notification-relation-wait-rolls-back-all-effects',async()=>lateWaitRollback('notification_relation'));
  await test('finish-lease-expiring-during-completion-receipt-trigger-wait-rolls-back-all-effects',async()=>lateWaitRollback('completion_update'));
  await test('exact-failed-operation-cleanup-preserves-unknown-and-existing-customer-paths',async()=>{const id=randomUUID(),c=canonical();c.manifest=[{digest:'a'.repeat(64),size:1,type:'image/png'}];const b=await begin(id,c),path=b.row.reference_paths[0];check(!(await db.storage.from('natori-inquiry-refs').upload(path,Buffer.from('temporary'),{contentType:'image/webp'})).error,'TEMP_OBJECT');check((await db.rpc('natori_intake_cleanup_scope_v1',{p_owner_id:owner,p_operation_id:id,p_request_hash:b.hash})).data?.length===0,'UNKNOWN_NO_CLEANUP');await db.from('natori_intake_operations').update({lease_expires_at:new Date(Date.now()-1000).toISOString()}).eq('owner_id',owner).eq('operation_id',id);check((await service.settlePublicIntakeOperation(id,b.hash)).kind==='failed','FAILED_SETTLE');check((await db.storage.from('natori-inquiry-refs').download(path)).error,'ONLY_EXACT_TEMP_REMOVED');});
  await test('late-inflight-upload-after-failed-settle-is-reclaimed-by-next-eligible-scan',async()=>{
   const png=await sharp({create:{width:3,height:3,channels:4,background:'#ffbbdd'}}).png().toBuffer(),id=randomUUID(),c=canonical();
   c.manifest=[{digest:createHash('sha256').update(png).digest('hex'),size:png.length,type:'image/png'}];
   const reached=new Promise<void>(resolve=>{observeUpload=resolve;});uploadRelease=new Promise<void>(resolve=>{releaseUpload=resolve;});fault='hold_upload';
   const pending=service.submitPublicIntakeOperation(id,c,[new File([png],'late.png',{type:'image/png'})]);
   try{
    await Promise.race([reached,new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error('UPLOAD_BOUNDARY_TIMEOUT')),10000))]);
    const before=await effects(id),path=before.row.reference_paths[0];check(before.row.status==='processing'&&before.project.length===0,'UPLOAD_IN_FLIGHT');
    check(!(await db.from('natori_intake_operations').update({lease_expires_at:new Date(Date.now()-1000).toISOString()}).eq('owner_id',owner).eq('operation_id',id)).error,'EXPIRE_UPLOAD_CLAIM');
    check((await service.settlePublicIntakeOperation(id,service.hashCanonicalIntake(c))).kind==='failed','UPLOAD_TOMBSTONE');
    releaseUpload();check((await pending).kind==='failed','LATE_UPLOAD_CANNOT_COMMIT');check(!(await db.storage.from('natori-inquiry-refs').download(path)).error,'LATE_OBJECT_EXISTS');
    const unknown=randomUUID(),u=await begin(unknown,c),unknownPath=u.row.reference_paths[0];
    check(!(await db.storage.from('natori-inquiry-refs').upload(unknownPath,await sharp(png).webp().toBuffer(),{contentType:'image/webp'})).error,'UNKNOWN_TEMP_FIXTURE');
    const linked=(await db.from('natori_inquiry_reference_files').select('storage_path')).data??[];check(linked.length>0,'COMMITTED_REFERENCE_CONTROL');
    const {scanNatoriInquiryReferenceOrphans}=await import('../../src/features/natori/server/inquiryOrphanService');
    const scan=await scanNatoriInquiryReferenceOrphans({dryRun:false,minimumAgeMs:0,maxDeletions:50});check(scan.kind==='ok'&&scan.deletedCount===1,'ONLY_FAILED_LATE_OBJECT_RECLAIMED');
    check((await db.storage.from('natori-inquiry-refs').download(path)).error,'LATE_OBJECT_REMOVED');
    check(!(await db.storage.from('natori-inquiry-refs').download(unknownPath)).error,'UNKNOWN_OBJECT_PRESERVED');
    for(const file of linked)check(!(await db.storage.from('natori-inquiry-refs').download(file.storage_path)).error,'COMMITTED_OBJECT_PRESERVED');
    const after=await effects(id);check(after.row.status==='failed'&&after.project.length===0&&after.notices.length===0&&after.refs.length===0,'TOMBSTONE_PRESERVED');
   }finally{releaseUpload();await pending;}
  });
  await test('failed-intake-cleanup-storage-error-remains-eligible-for-durable-retry',async()=>{
   const id=randomUUID(),c=canonical();c.manifest=[{digest:'b'.repeat(64),size:1,type:'image/png'}];const b=await begin(id,c),path=b.row.reference_paths[0];
   check(!(await db.storage.from('natori-inquiry-refs').upload(path,Buffer.from('temporary'),{contentType:'image/webp'})).error,'FAILED_TEMP_OBJECT');
   check(!(await db.from('natori_intake_operations').update({lease_expires_at:new Date(Date.now()-1000).toISOString()}).eq('owner_id',owner).eq('operation_id',id)).error,'FAILED_TEMP_EXPIRY');
   const settled=await db.rpc('natori_intake_settle_v1',{p_owner_id:owner,p_operation_id:id,p_request_hash:b.hash});check(!settled.error&&settled.data?.[0]?.result==='failed','FAILED_TEMP_SETTLE');
   const {scanNatoriInquiryReferenceOrphans}=await import('../../src/features/natori/server/inquiryOrphanService');fault='remove';
   check((await scanNatoriInquiryReferenceOrphans({dryRun:false,minimumAgeMs:0,maxDeletions:50})).kind==='unavailable','REMOVE_FAILURE_REPORTED');
   check(!(await db.storage.from('natori-inquiry-refs').download(path)).error&&(await op(id)).status==='failed','FAILED_ROW_OBJECT_RETAINED');
   const retry=await scanNatoriInquiryReferenceOrphans({dryRun:false,minimumAgeMs:0,maxDeletions:50});check(retry.kind==='ok'&&retry.deletedCount===1,'REMOVE_RETRY_SUCCEEDED');
   check((await db.storage.from('natori-inquiry-refs').download(path)).error&&(await op(id)).status==='failed','RETRY_KEEPS_FAILED_TOMBSTONE');
  });
  await test('old-no-id-csrf-origin-honeypot-and-anonymous-rpc-have-zero-sideeffects',async()=>{const before=(await db.from('natori_intake_operations').select('operation_id')).data?.length??0;const make=()=>new Request('http://localhost/api/natori/portfolio/contact',{method:'POST',headers:{'content-type':'application/json','x-requested-with':'me-ish'},body:JSON.stringify({name:'Old',email:'client@phase3a.invalid',message:'Old client'})});check((await route.POST(make())).status===409,'OLD_REJECT');check((await post(randomUUID(),canonical(),randomUUID(),false)).status===403,'CSRF');const wrong=make();wrong.headers.set('origin','https://attacker.invalid');check((await route.POST(wrong)).status===403,'ORIGIN');const anon=createClient(origin,keys.anon,{auth:{persistSession:false}});check((await anon.rpc('natori_intake_lookup_v1',{p_owner_id:owner,p_operation_id:randomUUID(),p_request_hash:'a'.repeat(64)})).error,'ANON_DENIED');check(((await db.from('natori_intake_operations').select('operation_id')).data?.length??0)===before,'NO_SIDE_EFFECT');});
  writeFileSync('/results/phase3a-integration.json',JSON.stringify({tests:results,passed:results.filter(t=>t.status==='passed').length,failed:results.filter(t=>t.status==='failed').length,skipped:0,provider:'real ephemeral PostgreSQL and Storage; notification sending disabled',blockedDestinations:blocked},null,2));
  check(results.length===26&&results.every(t=>t.status==='passed'),'REQUIRED_TESTS_FAILED');console.log('PHASE 3A 26 passed / 0 failed / 0 skipped; real mail pending');
 }finally{globalThis.fetch=direct;}
}
main().catch(()=>{console.error('Phase3A integration failed; raw payloads and credentials withheld');process.exitCode=1;});
