import {readFileSync,writeFileSync} from 'node:fs';
import {randomBytes,createHash} from 'node:crypto';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire('/app/package.json'),{createClient}=require('@supabase/supabase-js'),{chromium,expect}=require('@playwright/test');
const results=[],check=(ok,code)=>{if(!ok)throw new Error(code);};let browser,server;const errors=new Set();
const diagnosticStages=new Set(['CASE','ENTERED','DRAFT_SELECTED','COMMIT_REQUEST_CAPTURED','COMMIT_RESPONSE_OK','COMMIT_RESPONSE_ABORTED','LOST_ALERT','PENDING_FROZEN','ROUTE_REMOVED','PAGE_RELOADED','COMPOSER_ENABLED','COMPOSER_EMPTY','HISTORY_VISIBLE','FACTS_VERIFIED','RETRY_RELOADED','RETRY_CLICK','RETRY_RESPONSE','RETRY_ALERT','RETRY_FACTS']);
let stage='CASE';
const mark=value=>{stage=diagnosticStages.has(value)?value:'CASE';};
const diagnosticCodes=new Set(['EPHEMERAL_REQUIRED','DESTINATION_REJECTED','AUTH_FIXTURE','NEXT_READY','PROJECT_FIXTURE','ACCESS_FIXTURE','FACT_READ','ANON_DENIED','STAFF_CSRF_DENIED','CLIENT_CSRF_DENIED','SELECTION_IS_LOCAL','NO_RESERVATION_AFTER_CANCEL','UNIFIED_COMMIT','ONE_ACCESS_ONLY_STAFF','MOBILE_NO_OVERFLOW','COMMITTED_RESPONSE','COMMIT_INTERCEPTION_TIMEOUT','ORIGINAL_MESSAGE_RECOVERED','NOTICE_FAILED','SENDING_DISABLED_TRUTHFUL','MAIL_RETRY_ALONE','BROWSER_FAILED']);
function classifyFailure(error){
 const message=typeof error?.message==='string'?error.message:'';
 return {code:diagnosticCodes.has(message)?message:'ASSERTION_FAILED',kind:message.includes('strict mode violation')?'strict_locator':error?.name==='TimeoutError'||/\bTimeout\s+\d+ms\s+exceeded\b/i.test(message)?'timeout':error?.name==='AssertionError'||/^expect(?:\(|\.)/.test(message)||diagnosticCodes.has(message)?'assertion':'other',stage:diagnosticStages.has(stage)?stage:'CASE'};
}
async function waitForInterception(promise){let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('COMMIT_INTERCEPTION_TIMEOUT')),30000);})]);}finally{clearTimeout(timer);}}
const save=()=>writeFileSync('/results/phase3b-browser.json',JSON.stringify({tests:results,passed:results.filter(row=>row.status==='passed').length,failed:results.filter(row=>row.status==='failed').length,skipped:0,compileErrors:[...errors],engine:'Chromium 1.58.2, 390px viewport; iPhone Safari manual acceptance pending',realStorage:true,realMail:false},null,2));
async function test(name,fn){mark('CASE');try{await fn();results.push({name,status:'passed'});console.log('PASS phase3b-browser/'+name);}catch(e){results.push({name,status:'failed',...classifyFailure(e)});console.log('FAIL phase3b-browser/'+name);}save();}
async function main(){
 check(process.env.PHASE_N_BROWSER==='ephemeral','EPHEMERAL_REQUIRED');const {origin}=JSON.parse(readFileSync('/runtime/network.json','utf8'));check(/^http:\/\/172\.30\.250\.\d+:8000$/.test(origin),'DESTINATION_REJECTED');const keys=JSON.parse(readFileSync('/runtime/credentials.json','utf8'));
 const admin=createClient(origin,keys.service,{auth:{persistSession:false,autoRefreshToken:false}}),email='phase3b-owner@phase0b-browser.invalid',password=randomBytes(32).toString('hex');const auth=await admin.auth.admin.createUser({email,password,email_confirm:true});check(auth.data.user&&!auth.error,'AUTH_FIXTURE');const owner=auth.data.user.id,app='http://localhost:3000';
 server=spawn(process.execPath,['/app/node_modules/next/dist/bin/next','dev','--hostname','localhost','--port','3000'],{cwd:'/app',env:{PATH:'/runtime-bin:/usr/local/bin:/usr/bin:/bin',HOME:'/tmp',TMPDIR:'/tmp',NODE_ENV:'development',NODE_OPTIONS:'--dns-result-order=ipv4first',NEXT_TELEMETRY_DISABLED:'1',PHASE_0B_BROWSER:'ephemeral',PHASE_3B_BROWSER:'ephemeral',NEXT_PUBLIC_SUPABASE_URL:origin,NEXT_PUBLIC_SUPABASE_ANON_KEY:keys.anon,SUPABASE_SERVICE_ROLE_KEY:keys.service,NATORI_DASHBOARD_KEY:randomBytes(32).toString('hex'),NATORI_OWNER_USER_ID:owner,NATORI_OWNER_EMAILS:email,NEXT_PUBLIC_SITE_URL:app,NATORI_ACCEPTANCE_OUTBOX_ENABLED:'1',NATORI_NOTIFICATION_SENDING_ENABLED:'0',NATORI_DELIVERY_NOTIFICATION_KEY:randomBytes(32).toString('hex'),NATORI_ORDER_MAIL_FROM:'Fixture <sender@phase3b.invalid>',NATORI_PORTFOLIO_CONTACT_TO:'artist@phase3b.invalid'},stdio:['ignore','pipe','pipe']});
 for(const stream of [server.stdout,server.stderr])stream.on('data',bytes=>{for(const code of ['Module not found','Failed to compile','SyntaxError','EADDRINUSE'])if(bytes.toString().includes(code))errors.add(code);});
 let ready=false;for(let n=0;n<200&&server.exitCode===null;n++){try{if((await fetch(app+'/ja/fixture-session',{signal:AbortSignal.timeout(2000)})).ok){ready=true;break;}}catch{}await new Promise(resolve=>setTimeout(resolve,400));}check(ready,'NEXT_READY');
 browser=await chromium.launch({headless:true,args:['--host-resolver-rules=MAP localhost 127.0.0.1']});const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();
 await context.route('**/*',route=>[app,origin].includes(new URL(route.request().url()).origin)?route.continue():route.abort('blockedbyclient'));
 await page.goto(app+'/ja/fixture-session');await page.getByLabel('Email').fill(email);await page.getByLabel('Password').fill(password);await page.getByRole('button',{name:'Sign in'}).click();await expect(page.getByText('Session ready')).toBeVisible();
 async function setup(mode){const p=await admin.from('natori_projects').insert({user_id:owner,title:'Browser consultation',client_name:'Synthetic',client_email:'client@phase3b.invalid',type:'illustration',status:'inquiry',request_data:{message:'Original request preserved'}}).select('id').single();check(p.data&&!p.error,'PROJECT_FIXTURE');const token=randomBytes(32).toString('base64url');check(!(await admin.from('natori_consultation_access').insert({project_id:p.data.id,token_hash:createHash('sha256').update(token).digest('hex'),expires_at:new Date(Date.now()+86400000).toISOString()})).error,'ACCESS_FIXTURE');return{id:p.data.id,token,url:app+(mode==='staff'?'/ja/fixture-consultation/'+p.data.id:'/ja/natori/consult/'+token)};}
 const thread=()=>page.getByRole('region',{name:'相談のやり取り'}),send=()=>thread().getByRole('button',{name:'メッセージを送信',exact:true}),text=()=>thread().getByRole('textbox');
 const fixtureFile={name:'fixture.png',mimeType:'image/png',buffer:Buffer.from('synthetic browser PNG bytes')};
 const select=()=>page.getByLabel('相談ファイルを選ぶ').setInputFiles(fixtureFile);
 async function enter(i){await page.goto(i.url);await expect(send()).toBeVisible();await expect(text()).toBeEnabled();}
 async function facts(i){const rows=await Promise.all(['natori_consultation_messages','natori_consultation_files','natori_consultation_uploads','natori_notification_jobs','natori_consultation_access'].map(table=>admin.from(table).select('*').eq('project_id',i.id)));check(rows.every(r=>!r.error),'FACT_READ');return rows.map(row=>row.data??[]);}
 await test('actual-authentication-and-csrf-boundaries',async()=>{const i=await setup('staff');const anon=await browser.newContext();check((await anon.request.post(app+'/api/natori/admin/consultation',{data:{projectId:i.id},headers:{'x-requested-with':'me-ish'}})).status()===401,'ANON_DENIED');check((await context.request.post(app+'/api/natori/admin/consultation',{data:{projectId:i.id}})).status()===403,'STAFF_CSRF_DENIED');check((await context.request.post(app+'/api/natori/consult/'+i.token,{data:{body:'forbidden'}})).status()===403,'CLIENT_CSRF_DENIED');await anon.close();});
 for(const mode of ['staff','client']){
  await test(mode+'-local-selection-and-cancel-send-nothing',async()=>{const i=await setup(mode);await enter(i);await text().fill('Draft stays');await select();await expect(page.getByRole('button',{name:'fixture.pngの添付を取り消す'})).toBeVisible();const [m,f,u,n]=await facts(i);check(m.length+f.length+u.length+n.length===0,'SELECTION_IS_LOCAL');await page.getByRole('button',{name:'fixture.pngの添付を取り消す'}).click();await expect(text()).toHaveValue('Draft stays');check((await facts(i))[2].length===0,'NO_RESERVATION_AFTER_CANCEL');});
  for(const shape of ['text','file','combined'])await test(mode+'-'+shape+'-one-message-and-one-notice',async()=>{const i=await setup(mode);await enter(i);if(shape!=='file')await text().fill('Unified '+mode+' '+shape);if(shape!=='text')await select();await expect(send()).toBeEnabled();await send().click();await expect(thread().getByText(/送信を保存しました/)).toBeVisible();const [m,f,u,n,a]=await facts(i);check(m.length===1&&f.length===(shape==='text'?0:1)&&u.length===f.length&&u.every(row=>row.finalized_at&&row.message_id===m[0].id)&&n.length===1,'UNIFIED_COMMIT');check(a.length===(mode==='staff'?2:1),'ONE_ACCESS_ONLY_STAFF');await expect(text()).toHaveValue('');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'MOBILE_NO_OVERFLOW');});
  await test(mode+'-lost-finalize-response-reload-replays-one-message',async()=>{
   const i=await setup(mode);await enter(i);mark('ENTERED');await text().fill('Lost response fixture');await select();mark('DRAFT_SELECTED');
   let saved,resolve,interceptionError,active=true;const done=new Promise(r=>resolve=r),interceptionStage=value=>{if(active)mark(value);};
   await page.route('**/api/natori/**',async route=>{
    const req=route.request();if(req.method()!=='POST')return route.continue();let body;try{body=req.postDataJSON();}catch{return route.continue();}if(body.action!=='commit')return route.continue();
    try{interceptionStage('COMMIT_REQUEST_CAPTURED');saved=body.operation;const response=await route.fetch();check(response.ok(),'COMMITTED_RESPONSE');interceptionStage('COMMIT_RESPONSE_OK');await route.abort('failed');interceptionStage('COMMIT_RESPONSE_ABORTED');}
    catch(error){interceptionError=error;await route.abort('failed').catch(()=>{});}
    finally{resolve();}
   });
   try{
    await send().click();await waitForInterception(done);if(interceptionError)throw interceptionError;
    mark('LOST_ALERT');await expect(thread().getByRole('alert')).toBeVisible();mark('PENDING_FROZEN');await expect(text()).toBeDisabled();
    await page.unroute('**/api/natori/**');mark('ROUTE_REMOVED');await page.reload();mark('PAGE_RELOADED');
    // The restored composer can temporarily share its exact text with the saved history row.
    // Wait for the same confirmed-recovery predicates before the original history assertion.
    mark('COMPOSER_ENABLED');await expect(text()).toBeEnabled();mark('COMPOSER_EMPTY');await expect(text()).toHaveValue('');
    mark('HISTORY_VISIBLE');await expect(thread().getByText('Lost response fixture',{exact:true})).toBeVisible();
    mark('FACTS_VERIFIED');check(saved?.operationId&&((await facts(i))[0].length===1)&&((await facts(i))[3].length===1),'ORIGINAL_MESSAGE_RECOVERED');
   }finally{active=false;await page.unroute('**/api/natori/**').catch(()=>{});}
  });
 }
 await test('notification-retry-does-not-add-message-file-or-access',async()=>{const i=await setup('staff');await enter(i);await text().fill('Saved message');await send().click();await expect(thread().getByText(/送信を保存しました/)).toBeVisible();const before=await facts(i);check(!(await admin.from('natori_notification_jobs').update({status:'failed',error_code:'synthetic'}).eq('id',before[3][0].id)).error,'NOTICE_FAILED');await page.reload();mark('RETRY_RELOADED');const response=page.waitForResponse(r=>r.url()===app+'/api/natori/admin/consultation'&&r.request().method()==='POST',{timeout:30000});void response.catch(()=>{});mark('RETRY_CLICK');await page.getByRole('button',{name:'メール通知に失敗 · 再送する'}).click();mark('RETRY_RESPONSE');check((await response).status()===409,'SENDING_DISABLED_TRUTHFUL');mark('RETRY_ALERT');await expect(thread().getByRole('alert')).toBeVisible();mark('RETRY_FACTS');const after=await facts(i);check(after[0].length===before[0].length&&after[1].length===before[1].length&&after[4].length===before[4].length,'MAIL_RETRY_ALONE');});
 await test('failed-history-load-blocks-send-and-preserves-visible-history',async()=>{const i=await setup('client');await enter(i);await page.route('**/api/natori/consult/*',r=>r.request().method()==='GET'?r.fulfill({status:503,contentType:'application/json',body:'{}'}):r.continue());await page.getByRole('button',{name:'履歴を更新'}).click();await expect(thread().getByRole('alert')).toBeVisible();await text().fill('Wait');await expect(send()).toBeDisabled();await page.unroute('**/api/natori/consult/*');});
 await context.close();save();check(results.length===13&&results.every(row=>row.status==='passed')&&errors.size===0,'BROWSER_FAILED');
}
main().catch(()=>{save();console.error('Phase3B sealed browser failed');process.exitCode=1;}).finally(async()=>{await browser?.close();if(server&&server.exitCode===null){server.kill('SIGTERM');await Promise.race([new Promise(resolve=>server.once('exit',resolve)),new Promise(resolve=>setTimeout(resolve,5000))]);if(server.exitCode===null)server.kill('SIGKILL');}});
