import {createClient} from '@supabase/supabase-js';
import {readFileSync,writeFileSync} from 'node:fs';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import Stripe from 'stripe';
import {NextRequest} from 'next/server';
const check=(v:unknown,c:string)=>{if(!v)throw new Error(c);};
const results:{name:string;status:string;code?:string}[]=[];
async function test(name:string,fn:()=>Promise<void>){try{await fn();results.push({name,status:'passed'});console.log(`PASS phase2c/${name}`);}catch(e){const code=e instanceof Error&&/^[A-Z_0-9]+$/.test(e.message)?e.message:'ASSERTION_FAILED';results.push({name,status:'failed',code});console.log(`FAIL phase2c/${name} ${code}`);}}
async function main(){
 const {origin}=JSON.parse(readFileSync('/runtime/network.json','utf8'));check(/^http:\/\/172\.30\.250\.\d+:8000$/.test(origin),'DESTINATION_REJECTED');
 const keys=JSON.parse(readFileSync('/runtime/credentials.json','utf8'));
 const db=createClient(origin,keys.service,{auth:{persistSession:false}}),peer=createClient(origin,keys.service,{auth:{persistSession:false}});
 const direct=globalThis.fetch;let fault:'claim'|'complete'|null=null,lostStage:string|null=null,blocked=0;
 globalThis.fetch=async(input,init)=>{const u=new URL(typeof input==='string'?input:input instanceof URL?input.href:input.url);if(u.origin!==origin){blocked++;throw new Error('DESTINATION_REJECTED');}
  if(fault==='claim'&&u.pathname.endsWith('/rpc/natori_stripe_event_claim_v1')){fault=null;return new Response('{}',{status:503});}
  const response=await direct(input,init);if(lostStage&&u.pathname.endsWith('/rpc/natori_payment_links_v1')&&typeof init?.body==='string'){const body=JSON.parse(init.body);if(body.p_command==='stage'&&body.p_input.stage===lostStage){lostStage=null;check(response.ok,'STAGE_COMMITTED');return new Response('{}',{status:503});}}if(fault==='complete'&&u.pathname.endsWith('/rpc/natori_stripe_event_complete_v1')){fault=null;check(response.ok,'COMMITTED');return new Response('{}',{status:503});}return response;};
 try{
  const auth=await db.auth.admin.createUser({email:'owner@phase2c.invalid',password:randomBytes(32).toString('hex'),email_confirm:true});check(auth.data.user,'AUTH_FIXTURE');const owner=auth.data.user!.id;
  const signingSecret='whsec_'+randomBytes(32).toString('hex');
  Object.assign(process.env,{NEXT_PUBLIC_SUPABASE_URL:origin,NEXT_PUBLIC_SUPABASE_ANON_KEY:keys.anon,SUPABASE_SERVICE_ROLE_KEY:keys.service,
   STRIPE_SECRET_KEY:'sk_test_'+randomBytes(32).toString('hex'),STRIPE_WEBHOOK_SECRET:signingSecret,
   NATORI_OWNER_USER_ID:owner,NATORI_PAYMENT_INTEGRITY_ENABLED:'1',NATORI_STRIPE_MODE:'test',
   NATORI_ACCEPTANCE_OUTBOX_ENABLED:'1',NATORI_NOTIFICATION_SENDING_ENABLED:'0',RESEND_API_KEY:'',ADMIN_API_TOKEN:''});
  const route=await import('../../src/app/api/webhook/stripe/route');
  const {normalizeNatoriPaymentEvent}=await import('../../src/features/natori/lib/paymentEvent');
  const stripe=new Stripe(process.env.STRIPE_SECRET_KEY!);
  async function setup(){const p=await db.from('natori_projects').insert({user_id:owner,title:'Payment fixture',client_name:'Synthetic',client_email:'client@phase2c.invalid',type:'illustration',status:'inquiry',amount:12000,quoted_amount:12000}).select('id').single();check(!p.error&&p.data,'PROJECT');
   const q=await db.from('natori_quotes').insert({project_id:p.data!.id,user_id:owner,version:1,title:'Payment fixture',client_name:'Synthetic',to_email:'client@phase2c.invalid',amount:12000,subject:'Quote',body_snapshot:'Body',token_hash:createHash('sha256').update(randomUUID()).digest('hex'),expires_at:new Date(Date.now()+86400000).toISOString(),accepted_at:new Date().toISOString()}).select('id').single();check(!q.error&&q.data,'QUOTE');
   check(!(await db.from('natori_projects').update({status:'awaiting_payment',payment_quote_id:q.data!.id,active_quote_id:q.data!.id,quote_accepted_at:new Date().toISOString(),quote_accepted_amount:12000}).eq('id',p.data!.id)).error,'PAYMENT_QUOTE');
   return {projectId:p.data!.id,quoteId:q.data!.id,sessionId:'cs_test_'+randomUUID().replaceAll('-','')};}
  type Input=Awaited<ReturnType<typeof setup>>;
  function event(input:Input,options:{id?:string;amount?:number;currency?:string;quoteId?:string;live?:boolean}={}):Stripe.Event{return {id:options.id??'evt_'+randomUUID().replaceAll('-',''),object:'event',type:'checkout.session.completed',livemode:options.live??false,created:Math.floor(Date.now()/1000),data:{object:{id:input.sessionId,object:'checkout.session',payment_status:'paid',status:'complete',amount_total:options.amount??12000,currency:options.currency??'jpy',payment_intent:'pi_test_'+randomUUID().replaceAll('-',''),metadata:{kind:'natori_commission',projectId:input.projectId,quoteId:options.quoteId??input.quoteId}}}} as unknown as Stripe.Event;}
  async function post(e:Stripe.Event,bad=false){const payload=JSON.stringify(e),signature=bad?'invalid':stripe.webhooks.generateTestHeaderString({payload,secret:signingSecret});return route.POST(new NextRequest('http://localhost/api/webhook/stripe',{method:'POST',body:payload,headers:{'stripe-signature':signature}}));}
  async function transactions(id:string){return (await db.from('natori_payment_transactions').select('*').eq('project_id',id)).data??[];}
  async function notices(id:string){return (await db.from('natori_notification_jobs').select('id,status,purpose').eq('project_id',id)).data??[];}
  async function claim(e:Stripe.Event,token:string){const normalized=normalizeNatoriPaymentEvent(e);return db.rpc('natori_stripe_event_claim_v1',{p_owner_id:owner,p_account:normalized.account,p_live:e.livemode,p_event_id:e.id,p_type:e.type,p_request:normalized.request,p_claim_token:token});}
  async function complete(e:Stripe.Event,token:string,generation:number,ownerId=owner){return peer.rpc('natori_stripe_event_complete_v1',{p_owner_id:ownerId,p_account:'platform',p_live:e.livemode,p_event_id:e.id,p_claim_token:token,p_generation:generation});}
  const {executePaymentLinkOperation,getPaymentLinkState,stopDuePaymentLinks}=await import('../../src/features/natori/server/paymentLinkService');
  const {paymentLinkRequestSchema}=await import('../../src/features/natori/lib/paymentLinkRequest');
  const {natoriManagementScope}=await import('../../src/features/natori/server/natoriManagementScope');
  Object.assign(process.env,{NATORI_PAYMENT_LINK_INTEGRITY_ENABLED:'1',NATORI_QUOTE_INTEGRITY_ENABLED:'1',NATORI_DELIVERY_NOTIFICATION_KEY:randomBytes(32).toString('hex'),
   NATORI_ORDER_MAIL_FROM:'Fixture <sender@phase2c.invalid>',NATORI_PORTFOLIO_CONTACT_TO:'artist@phase2c.invalid'});
  const scoped=<T>(fn:()=>Promise<T>)=>natoriManagementScope.run({ownerId:owner,operator:{kind:'auth-user',userId:owner}},fn);
  const links=new Map<string,{id:string;url:string;active:boolean;livemode:boolean;projectId:string;quoteId:string;amount:number|null;currency:string|null;kind?:string;attemptId?:string;generation?:string;priceId?:string}>();
  function provider(){const prices=new Map<string,string>(),keys=new Map<string,string>();let failure:'price'|'link'|null=null;let hook:(()=>Promise<void>)|null=null;
   const ext={
    accountId:async()=>'acct_phase2cfixture',
    createPrice:async(a:{id:string},key:string)=>{let id=prices.get(key);if(!id){id='price_'+randomUUID().replaceAll('-','');prices.set(key,id);}if(failure==='price'){failure=null;throw new Error('SYNTHETIC_RESPONSE_LOSS');}return id;},
    createLink:async(a:{id:string;generation:number;project_id:string;quote_id:string;livemode:boolean;amount:number},price:string,key:string)=>{let id=keys.get(key);if(!id){id='plink_'+randomUUID().replaceAll('-','');keys.set(key,id);links.set(id,{id,url:'https://buy.stripe.com/'+id,active:true,livemode:a.livemode,projectId:a.project_id,quoteId:a.quote_id,amount:a.amount,currency:'jpy',kind:'natori_commission',attemptId:a.id,generation:String(a.generation),priceId:price});}if(hook){const callback=hook;hook=null;await callback();}if(failure==='link'){failure=null;throw new Error('SYNTHETIC_RESPONSE_LOSS');}return links.get(id)!;},
    findLink:async(a:{id:string;project_id:string;quote_id:string;generation:number;livemode:boolean;amount:number;price_id:string|null},heartbeat:()=>Promise<void>)=>{
     await heartbeat();const matches=[...links.values()].filter(link=>link.attemptId===a.id);
     if(matches.length>1)throw new Error('FIXTURE_RECONCILIATION_AMBIGUOUS');
     const link=matches[0];if(!link)return null;
     if(link.kind!=='natori_commission'||link.projectId!==a.project_id||link.quoteId!==a.quote_id||link.generation!==String(a.generation)
      ||link.livemode!==a.livemode||link.amount!==a.amount||link.currency!=='jpy'||(a.price_id!==null&&link.priceId!==a.price_id))throw new Error('FIXTURE_RECONCILIATION_UNVERIFIED');
     await heartbeat();return {...link};
    },
    readLink:async(id:string)=>{const link=links.get(id);if(!link)throw new Error('FIXTURE_LINK_UNKNOWN');return {...link};},
    sessions:async(_id:string)=>[] as {id:string;status:string|null;paymentStatus:string}[],expireSession:async(_id:string)=>{},
    stopLink:async(id:string)=>{const link=links.get(id);if(!link)throw new Error('FIXTURE_LINK_UNKNOWN');link.active=false;},
   };return {ext,prices,keys,fail:(value:'price'|'link')=>{failure=value;},onLink:(callback:()=>Promise<void>)=>{hook=callback;}};
  }
  const deadline=()=>new Date(Date.now()+7*86400000).toISOString();
  const request=(id:string,extra:Record<string,unknown>={})=>({projectId:id,operationId:randomUUID(),action:'issue',deadline:deadline(),to:'client@phase2c.invalid',subject:'Payment fixture',body:'Synthetic body {支払リンク}',...extra});
  async function call(id:string,command:string,input:Record<string,unknown>={},client=db){const r=await client.rpc('natori_payment_links_v1',{p_owner_id:owner,p_project_id:id,p_command:command,p_input:input});if(r.error)throw new Error('RPC_'+command.toUpperCase());return r.data;}
  const run=(input:unknown,ext:ReturnType<typeof provider>['ext'])=>scoped(()=>executePaymentLinkOperation(input,ext));
  const view=(id:string)=>scoped(()=>getPaymentLinkState(id));
  const expireLease=async(id:string)=>{check(!(await db.from('natori_payment_link_attempts').update({lease_until:new Date(Date.now()-1000).toISOString()}).eq('project_id',id)).error,'FIXTURE_LEASE');};
  const beginInput=(raw:unknown,token:string)=>{const input=paymentLinkRequestSchema.parse(raw);return {operationId:input.operationId,token,hash:createHash('sha256').update(JSON.stringify(input)).digest('hex'),action:input.action,livemode:false,providerAccountId:'acct_phase2cfixture',deadline:input.deadline??null,revision:input.revision??null,confirmed:input.confirmed??false};};
  await test('issue-commits-generation-operation-and-encrypted-notification',async()=>{const i=await setup(),f=provider(),r=await run(request(i.projectId),f.ext);check(r.result==='completed','ISSUED');const v=await view(i.projectId);check(v.state==='active'&&v.generation===1&&v.revision===1,'ACTIVE');const jobs=await db.from('natori_notification_jobs').select('purpose,payload').eq('project_id',i.projectId);check(jobs.data?.length===1&&jobs.data[0].purpose==='payment_link_client'&&jobs.data[0].payload?.format==='natori-delivery-aes256gcm-v1','ENCRYPTED_NOTICE');check(!JSON.stringify(jobs.data).includes('client@'),'NO_PLAINTEXT');});
  await test('concurrent-different-operations-cannot-create-two-generations',async()=>{const i=await setup(),f=provider(),done=await Promise.all([run(request(i.projectId),f.ext),run(request(i.projectId),f.ext)]);check(done.some(r=>r.result==='completed'),'ONE_COMPLETES');check((await db.from('natori_payment_link_attempts').select('id').eq('project_id',i.projectId)).data?.length===1&&f.keys.size===1,'ONE_LINK');});
  await test('completed-response-loss-replays-same-operation-notice',async()=>{const i=await setup(),f=provider(),req=request(i.projectId);check((await run(req,f.ext)).result==='completed','FIRST');check((await run(req,f.ext)).result==='completed','REPLAY');check(f.keys.size===1&&(await db.from('natori_notification_jobs').select('id').eq('project_id',i.projectId)).data?.length===1,'ONE_NOTICE');check((await run({...req,body:'Changed content'},f.ext)).result==='conflict','HASH_CONFLICT');});
  await test('price-response-loss-recovers-the-same-provider-key',async()=>{const i=await setup(),f=provider(),req=request(i.projectId);f.fail('price');check((await run(req,f.ext)).result==='retry_same_operation','INTERRUPTED');await expireLease(i.projectId);check((await run(req,f.ext)).result==='completed'&&f.prices.size===1&&f.keys.size===1,'RECOVERED_PRICE');});
  await test('link-response-loss-recovers-the-same-provider-key',async()=>{const i=await setup(),f=provider(),req=request(i.projectId);f.fail('link');check((await run(req,f.ext)).result==='retry_same_operation','INTERRUPTED');await expireLease(i.projectId);check((await run(req,f.ext)).result==='completed'&&f.prices.size===1&&f.keys.size===1,'RECOVERED_LINK');});
  await test('committed-stage-response-loss-reuses-known-price-id',async()=>{const i=await setup(),f=provider(),req=request(i.projectId);lostStage='price';check((await run(req,f.ext)).result==='retry_same_operation','DB_ACK_LOST');await expireLease(i.projectId);check((await run(req,f.ext)).result==='completed'&&f.prices.size===1,'KNOWN_PRICE');});
  await test('expired-worker-is-fenced-by-a-second-db-connection',async()=>{const i=await setup(),req=request(i.projectId),a=randomUUID(),b=randomUUID(),first=await call(i.projectId,'begin',beginInput(req,a));check(first.result==='claimed','CLAIM');await expireLease(i.projectId);const second=await call(i.projectId,'begin',beginInput(req,b),peer);check(second.result==='claimed'&&second.attempt.claim_generation>first.attempt.claim_generation,'RECLAIM');const stale=await call(i.projectId,'stage',{operationId:req.operationId,token:a,generation:first.attempt.claim_generation,stage:'price',value:{id:'price_stale'}});check(stale.result==='stale','FENCED');check((await db.from('natori_payment_link_attempts').select('price_id').eq('project_id',i.projectId).single()).data?.price_id===null,'NO_STALE_EFFECT');});
  await test('unknown-result-after-key-retention-window-never-blindly-recreates',async()=>{const i=await setup(),f=provider(),req=request(i.projectId);f.fail('price');await run(req,f.ext);await expireLease(i.projectId);await db.from('natori_payment_link_attempts').update({price_started_at:new Date(Date.now()-24*3600000).toISOString()}).eq('project_id',i.projectId);check((await run(req,f.ext)).result==='needs_review'&&f.prices.size===1&&f.keys.size===0,'RETENTION_GATE');});
  await test('renotify-keeps-the-same-url-generation-and-deadline',async()=>{const i=await setup(),f=provider();await run(request(i.projectId),f.ext);const before=await view(i.projectId);const req=request(i.projectId,{action:'renotify',revision:before.revision});delete (req as Partial<typeof req>).deadline;check((await run(req,f.ext)).result==='completed','RENOTIFY');const after=await view(i.projectId);check(after.url===before.url&&after.deadline===before.deadline&&after.generation===1&&after.revision===1,'DEADLINE_PRESERVED');check((await db.from('natori_notification_jobs').select('id').eq('project_id',i.projectId)).data?.length===2,'DISTINCT_NOTICE');});
  await test('extension-requires-confirmation-and-invalidates-stale-mail-deadline',async()=>{const i=await setup(),f=provider();await run(request(i.projectId),f.ext);const before=await view(i.projectId),notice=(await db.from('natori_notification_jobs').select('id').eq('project_id',i.projectId).single()).data!.id;
   const req={projectId:i.projectId,operationId:randomUUID(),action:'extend',revision:before.revision,deadline:new Date(Date.parse(before.deadline!)+86400000).toISOString(),confirmed:true};
   check((await run({...req,confirmed:false},f.ext)).result==='invalid_request','CONFIRM');check((await run(req,f.ext)).result==='completed','EXTENDED');const after=await view(i.projectId);check(after.revision===2&&after.url===before.url,'REVISION');check((await call(i.projectId,'mail_gate',{jobId:notice,token:randomUUID()})).result==='blocked','OLD_DEADLINE_NOT_SENT');check((await run({...req,operationId:randomUUID()},f.ext)).result==='conflict','STALE_REVISION');});
  await test('expiry-claim-blocks-competing-extension',async()=>{const i=await setup(),f=provider();await run(request(i.projectId),f.ext);const before=await view(i.projectId);await db.from('natori_payment_link_attempts').update({deadline:new Date(Date.now()-1000).toISOString()}).eq('project_id',i.projectId);check((await call(i.projectId,'queue_stop')).result==='queued','QUEUED');const done=await Promise.all([call(i.projectId,'claim_stop',{token:randomUUID()},peer),run({projectId:i.projectId,operationId:randomUUID(),action:'extend',revision:before.revision,deadline:deadline(),confirmed:true},f.ext)]);check(done[0].result==='claimed'&&done[1].result==='conflict','SERIALIZED_STOP');});
  await test('close-during-provider-create-records-stop-without-mail-or-reopen',async()=>{const i=await setup(),f=provider();f.onLink(async()=>{check((await call(i.projectId,'close',{reason:'Synthetic close'})).result==='completed','CLOSED');});check((await run(request(i.projectId),f.ext)).result==='invalid_state','NO_NOTICE');check((await db.from('natori_notification_jobs').select('id').eq('project_id',i.projectId)).data?.length===0,'NO_MAIL');check((await view(i.projectId)).terminal,'TERMINAL');await expireLease(i.projectId);await stopDuePaymentLinks(f.ext);check((await view(i.projectId)).state==='inactive','STOP_CONFIRMED');});
  await test('archive-is-rejected-until-terminal-link-stop-is-confirmed',async()=>{const i=await setup(),f=provider();await run(request(i.projectId),f.ext);check((await call(i.projectId,'archive')).result==='unresolved','ACTIVE_ARCHIVE_DENIED');await call(i.projectId,'close');check((await call(i.projectId,'archive')).result==='unresolved','STOP_PENDING');await stopDuePaymentLinks(f.ext);check((await call(i.projectId,'archive')).result==='completed','RESOLVED_ARCHIVE');});
  await test('closed-delayed-checkout-retains-money-without-reopening',async()=>{const i=await setup(),f=provider();await run(request(i.projectId),f.ext);await call(i.projectId,'close');check((await post(event(i))).status===200,'PAYMENT_ACK');const p=await db.from('natori_projects').select('status,payment_confirmed_at,paid_amount').eq('id',i.projectId).single();check(p.data?.status==='closed'&&p.data.payment_confirmed_at&&p.data.paid_amount===12000,'MONEY_RETAINED');check((await run(request(i.projectId),f.ext)).result==='invalid_state','NO_NEW_LINK');});
  await test('inactive-provider-link-cannot-be-successfully-renotified',async()=>{const i=await setup(),f=provider();await run(request(i.projectId),f.ext);const v=await view(i.projectId);links.get(v.url!.split('/').at(-1)!)!.active=false;const req=request(i.projectId,{action:'renotify',revision:v.revision});delete (req as Partial<typeof req>).deadline;check((await run(req,f.ext)).result==='needs_review','INACTIVE_NOT_SENT');check((await db.from('natori_notification_jobs').select('id').eq('project_id',i.projectId)).data?.length===1,'NO_NEW_NOTICE');});
  await test('manual-legacy-adoption-preserves-url-and-exact-old-deadline',async()=>{const i=await setup(),f=provider(),id='plink_'+randomUUID().replaceAll('-',''),url='https://buy.stripe.com/'+id,sent=new Date(Date.now()-2*86400000).toISOString();links.set(id,{id,url,active:true,livemode:false,projectId:i.projectId,quoteId:i.quoteId,amount:12000,currency:'jpy'});
   await db.from('natori_projects').update({payment_link_id:id,payment_link_url:url,payment_link_status:'sent'}).eq('id',i.projectId);
   check(!(await db.from('natori_order_mail_logs').insert({request_id:randomUUID(),project_id:i.projectId,kind:'payment',to_email:'client@phase2c.invalid',amount:12000,link_url:url,subject:'Synthetic',body_snapshot:'Synthetic',status:'sent',sent_at:sent})).error,'LOG');
   check((await run({projectId:i.projectId,operationId:randomUUID(),action:'adopt',confirmed:true},f.ext)).result==='completed','ADOPTED');const v=await view(i.projectId);check(v.url===url&&Date.parse(v.deadline!)===Date.parse(sent)+7*86400000,'EXACT_LEGACY_DEADLINE');check(f.keys.size===0&&f.prices.size===0,'NO_RECREATION');});
  await test('old-project-mail-writer-cannot-overwrite-generation-projection',async()=>{const i=await setup(),f=provider();await run(request(i.projectId),f.ext);check((await db.from('natori_projects').update({payment_link_status:'send_failed'}).eq('id',i.projectId)).error,'LEGACY_WRITER_DENIED');check((await view(i.projectId)).state==='active','FACTS_PRESERVED');});
  await test('mail-lease-serializes-external-stop-and-new-notification',async()=>{const i=await setup(),f=provider();await run(request(i.projectId),f.ext);const notice=(await db.from('natori_notification_jobs').select('id').eq('project_id',i.projectId).single()).data!.id,token=randomUUID();check((await call(i.projectId,'mail_gate',{jobId:notice,token})).result==='allowed','MAIL_CLAIM');await call(i.projectId,'close');check((await call(i.projectId,'claim_stop',{token:randomUUID()},peer)).result==='busy','STOP_WAIT');await call(i.projectId,'mail_gate',{jobId:notice,token,action:'release'});check((await call(i.projectId,'claim_stop',{token:randomUUID()},peer)).result==='claimed','STOP_AFTER_RELEASE');check((await call(i.projectId,'mail_gate',{jobId:notice,token:randomUUID()})).result==='blocked','TERMINAL_MAIL_BLOCKED');});
  await test('reissue-is-explicit-new-generation-and-stops-old-open-sessions',async()=>{const i=await setup(),f=provider();await run(request(i.projectId),f.ext);await db.from('natori_payment_link_attempts').update({deadline:new Date(Date.now()-1000).toISOString()}).eq('project_id',i.projectId);await stopDuePaymentLinks(f.ext);const old=await view(i.projectId);check(old.state==='inactive','OLD_STOPPED');let expired=0;f.ext.sessions=async()=>[{id:'cs_test_open',status:'open',paymentStatus:'unpaid'}];f.ext.expireSession=async()=>{expired++;};check((await run(request(i.projectId,{action:'reissue',confirmed:true}),f.ext)).result==='completed','REISSUED');const now=await view(i.projectId);check(now.generation===2&&now.url!==old.url&&expired===1,'NEW_GENERATION');});
  await test('paid-old-session-blocks-reissue-before-provider-create',async()=>{const i=await setup(),f=provider();await run(request(i.projectId),f.ext);await db.from('natori_payment_link_attempts').update({deadline:new Date(Date.now()-1000).toISOString()}).eq('project_id',i.projectId);await stopDuePaymentLinks(f.ext);f.ext.sessions=async()=>[{id:'cs_test_completed',status:'complete',paymentStatus:'paid'}];check((await run(request(i.projectId,{action:'reissue',confirmed:true}),f.ext)).result==='payment_review'&&f.keys.size===1,'PAID_NO_REISSUE');});
  const expireCreation=async(id:string)=>{check(!(await db.from('natori_payment_link_attempts').update({deadline:new Date(Date.now()-1000).toISOString(),lease_until:new Date(Date.now()-1000).toISOString()}).eq('project_id',id)).error,'FIXTURE_EXPIRED_CREATION');};
  const noCreationNotice=async(id:string)=>{check((await notices(id)).length===0,'NO_CREATION_NOTICE');const p=await db.from('natori_projects').select('status,payment_link_id,payment_confirmed_at').eq('id',id).single();check(p.data?.status==='awaiting_payment'&&p.data.payment_link_id===null&&p.data.payment_confirmed_at===null,'NO_PUBLICATION_OR_REOPEN');};
  await test('known-link-before-finish-is-stopped-after-deadline-without-publication',async()=>{const i=await setup(),f=provider();lostStage='link';check((await run(request(i.projectId),f.ext)).result==='retry_same_operation','LINK_ACK_LOST');const before=await db.from('natori_payment_link_attempts').select('state,link_id').eq('project_id',i.projectId).single();check(before.data?.state==='creating'&&before.data.link_id,'KNOWN_CREATING');await expireCreation(i.projectId);check((await call(i.projectId,'scan')).projects.includes(i.projectId),'SCANNED');await stopDuePaymentLinks(f.ext);check((await view(i.projectId)).state==='inactive'&&!links.get(before.data!.link_id!)!.active,'PROVIDER_STOPPED');await noCreationNotice(i.projectId);check(f.keys.size===1&&f.prices.size===1,'NO_RECREATION');});
  await test('unknown-link-after-response-loss-is-reconciled-and-stopped-at-deadline',async()=>{const i=await setup(),f=provider();f.fail('link');check((await run(request(i.projectId),f.ext)).result==='retry_same_operation','LINK_RESPONSE_LOST');check((await db.from('natori_payment_link_attempts').select('link_id').eq('project_id',i.projectId).single()).data?.link_id===null,'LINK_UNKNOWN');await expireCreation(i.projectId);await stopDuePaymentLinks(f.ext);const after=await db.from('natori_payment_link_attempts').select('state,link_id').eq('project_id',i.projectId).single();check(after.data?.state==='inactive'&&after.data.link_id&&!links.get(after.data.link_id)!.active,'RECONCILED_STOP');await noCreationNotice(i.projectId);check(f.keys.size===1&&f.prices.size===1,'NO_RECREATE_UNKNOWN');});
  await test('missing-unknown-provider-result-remains-review-without-blind-create',async()=>{const i=await setup(),f=provider();f.fail('link');await run(request(i.projectId),f.ext);for(const id of f.keys.values())links.delete(id);await expireCreation(i.projectId);await stopDuePaymentLinks(f.ext);const a=await db.from('natori_payment_link_attempts').select('state,link_id,review_reason,lease_until').eq('project_id',i.projectId).single();check(a.data?.state==='needs_review'&&a.data.link_id===null&&a.data.review_reason==='expired_creation_result_unresolved'&&a.data.lease_until===null,'MISSING_REVIEW');await noCreationNotice(i.projectId);check(f.keys.size===1&&f.prices.size===1,'NO_BLIND_RECREATE');check((await call(i.projectId,'archive')).result==='unresolved','REVIEW_NOT_ARCHIVABLE');});
  await test('future-creating-attempt-is-not-queued-for-early-stop',async()=>{const i=await setup(),f=provider();f.fail('price');await run(request(i.projectId),f.ext);await expireLease(i.projectId);check((await call(i.projectId,'queue_stop')).result==='not_due','FUTURE_NOT_DUE');check((await view(i.projectId)).state==='creating','CREATION_PRESERVED');});
  await test('reconciliation-lease-fences-prior-worker-save-renew-and-review',async()=>{const i=await setup(),f=provider();f.fail('link');await run(request(i.projectId),f.ext);await expireCreation(i.projectId);const firstToken=randomUUID(),secondToken=randomUUID(),first=await call(i.projectId,'reconcile_claim',{token:firstToken});check(first.result==='claimed','FIRST_RECONCILE');await expireLease(i.projectId);const second=await call(i.projectId,'reconcile_claim',{token:secondToken},peer);check(second.result==='claimed'&&second.attempt.claim_generation>first.attempt.claim_generation,'RECLAIM_RECONCILE');const known=links.get([...f.keys.values()][0])!,oldFence={token:firstToken,generation:first.attempt.claim_generation,providerAccountId:'acct_phase2cfixture'};for(const command of ['reconcile_renew','reconcile_review','reconcile_save'])check((await call(i.projectId,command,{...oldFence,linkId:known.id,url:known.url,verified:true})).result==='stale','OLD_RECONCILE_FENCED');check((await db.from('natori_payment_link_attempts').select('link_id,state').eq('project_id',i.projectId).single()).data?.link_id===null,'NO_OLD_SAVE');const fence={token:secondToken,generation:second.attempt.claim_generation,providerAccountId:'acct_phase2cfixture'};check((await call(i.projectId,'reconcile_renew',fence,peer)).result==='renewed','NEW_RENEWED');check((await call(i.projectId,'reconcile_save',{...fence,linkId:known.id,url:known.url,verified:true},peer)).result==='saved','NEW_SAVED');await stopDuePaymentLinks(f.ext);check((await view(i.projectId)).state==='inactive','FENCED_RESULT_STOPPED');await noCreationNotice(i.projectId);});
  await test('stop-lease-fences-expired-renew-finish-and-previous-generation',async()=>{const i=await setup(),f=provider();await run(request(i.projectId),f.ext);await expireCreation(i.projectId);await call(i.projectId,'queue_stop');const token=randomUUID(),first=await call(i.projectId,'claim_stop',{token});check(first.result==='claimed'&&first.attempt.id===first.job.attempt_id,'MATCHING_STOP_ATTEMPT');const oldFence={jobId:first.job.id,token,generation:first.job.claim_generation,providerAccountId:'acct_phase2cfixture'};check((await call(i.projectId,'stop_renew',oldFence)).result==='renewed','STOP_RENEW');check(!(await db.from('natori_payment_link_stops').update({lease_until:new Date(Date.now()-1000).toISOString()}).eq('id',first.job.id)).error,'STOP_LEASE_EXPIRED');check((await call(i.projectId,'stop_renew',oldFence)).result==='stale','EXPIRED_RENEW_DENIED');const second=await call(i.projectId,'claim_stop',{token:randomUUID()},peer);check(second.result==='claimed'&&second.job.claim_generation>first.job.claim_generation,'STOP_RECLAIM');check((await call(i.projectId,'finish_stop',{...oldFence,outcome:'inactive'})).result==='stale','OLD_STOP_FINISH_DENIED');const a=await view(i.projectId);check(a.state==='deactivating'&&links.get(a.url!.split('/').at(-1)!)!.active,'NO_STALE_STOP_COMMIT');await db.from('natori_payment_link_stops').update({lease_until:new Date(Date.now()-1000).toISOString()}).eq('id',second.job.id);await stopDuePaymentLinks(f.ext);check((await view(i.projectId)).state==='inactive','NEW_STOP_CONFIRMED');});
  await test('definitive-rejection-is-immutable-across-corrected-and-competing-operations',async()=>{const i=await setup(),f=provider(),bad=request(i.projectId,{deadline:new Date(Date.now()-1000).toISOString()});const rejected=await run(bad,f.ext);check(rejected.result==='invalid_deadline'&&'operationState' in rejected&&rejected.operationState==='rejected'&&'operationId' in rejected&&rejected.operationId===bad.operationId,'DEFINITIVE_REJECTED');check((await call(i.projectId,'rejection',{operationId:bad.operationId})).result==='rejected','RELOAD_REJECTION');check((await db.from('natori_payment_link_operations').select('operation_id').eq('project_id',i.projectId)).data?.length===0,'NO_REJECTED_OPERATION');const corrected={...bad,deadline:deadline()};check((await run(corrected,f.ext)).result==='conflict','IDENTITY_HASH_FENCE');const competing=await Promise.all([run(bad,f.ext),run({...corrected,operationId:randomUUID()},f.ext)]);check(competing[0].result==='invalid_deadline'&&competing[1].result==='completed','REJECTED_REPLAY_AND_NEW_SUCCESS');check((await run(bad,f.ext)).result==='invalid_deadline'&&f.keys.size===1,'REPLAY_AFTER_WINNER');const tombstone=await db.from('natori_payment_link_rejections').select('reason,request_hash').eq('project_id',i.projectId).single();check(tombstone.data?.reason==='invalid_deadline'&&tombstone.data.request_hash===beginInput(bad,randomUUID()).hash,'TOMBSTONE_UNCHANGED');check((await db.from('natori_payment_link_rejections').update({reason:'changed'}).eq('project_id',i.projectId)).error,'TOMBSTONE_UPDATE_DENIED');});
  await test('refusal-helper-cannot-tombstone-an-already-committed-operation',async()=>{const i=await setup(),f=provider(),req=request(i.projectId);check((await run(req,f.ext)).result==='completed','PUBLISHED');const refusal=await peer.rpc('natori_payment_link_reject_v1',{p_project:i.projectId,p_operation:req.operationId,p_hash:beginInput(req,randomUUID()).hash,p_reason:'invalid_deadline'});check(!refusal.error&&refusal.data?.result==='conflict','COMMITTED_NOT_REJECTED');check((await db.from('natori_payment_link_rejections').select('operation_id').eq('project_id',i.projectId)).data?.length===0,'NO_FALSE_TOMBSTONE');check((await run(req,f.ext)).result==='completed','COMPLETED_STILL_REPLAYS');});
  await test('inactive-legacy-adoption-voids-only-unpaid-projection-and-can-close-archive',async()=>{const i=await setup(),f=provider(),id='plink_'+randomUUID().replaceAll('-',''),url='https://buy.stripe.com/'+id,sent=new Date(Date.now()-2*86400000).toISOString();links.set(id,{id,url,active:false,livemode:false,projectId:i.projectId,quoteId:i.quoteId,amount:12000,currency:'jpy'});check(!(await db.from('natori_projects').update({payment_link_id:id,payment_link_url:url,payment_link_status:'sent'}).eq('id',i.projectId)).error,'LEGACY_PROJECTION');check(!(await db.from('natori_order_mail_logs').insert({request_id:randomUUID(),project_id:i.projectId,kind:'payment',to_email:'client@phase2c.invalid',amount:12000,link_url:url,subject:'Synthetic history',body_snapshot:'Synthetic history',status:'sent',sent_at:sent})).error,'LEGACY_LOG');check((await run({projectId:i.projectId,operationId:randomUUID(),action:'adopt',confirmed:true},f.ext)).result==='completed','INACTIVE_ADOPTED');const v=await view(i.projectId);check(v.state==='inactive'&&v.url===url&&Date.parse(v.deadline!)===Date.parse(sent)+7*86400000,'INACTIVE_FACTS');const projection=await db.from('natori_projects').select('payment_link_id,payment_link_url,payment_link_status,payment_confirmed_at').eq('id',i.projectId).single();check(projection.data?.payment_link_id===id&&projection.data.payment_link_url===url&&projection.data.payment_link_status==='void'&&projection.data.payment_confirmed_at===null,'UNPAID_PROJECTION_VOID');check((await call(i.projectId,'close')).result==='completed'&&(await call(i.projectId,'archive')).result==='completed','INACTIVE_LEGACY_ARCHIVABLE');check((await db.from('natori_order_mail_logs').select('body_snapshot,link_url,sent_at').eq('project_id',i.projectId)).data?.length===1&&(await notices(i.projectId)).length===0&&f.keys.size===0&&f.prices.size===0,'HISTORY_RETAINED_WITHOUT_NOTICE');});
  await test('known-generation-metadata-mismatch-blocks-provider-stop',async()=>{const i=await setup(),f=provider();await run(request(i.projectId),f.ext);const before=await view(i.projectId),link=links.get(before.url!.split('/').at(-1)!)!;link.generation='wrong';await expireCreation(i.projectId);await stopDuePaymentLinks(f.ext);check(link.active&&(await view(i.projectId)).state==='needs_review','UNVERIFIED_PROVIDER_NOT_STOPPED');});
  await test('provider-resource-missing-remains-unresolved-and-cannot-archive',async()=>{const i=await setup(),f=provider();await run(request(i.projectId),f.ext);await call(i.projectId,'close');f.ext.readLink=async()=>{throw Object.assign(new Error('FIXTURE_WRONG_ACCOUNT'),{code:'resource_missing'});};await stopDuePaymentLinks(f.ext);check((await view(i.projectId)).state==='needs_review'&&(await call(i.projectId,'archive')).result==='unresolved','MISSING_NOT_INACTIVE');const s=await db.from('natori_payment_link_stops').select('status').eq('project_id',i.projectId).single();check(s.data?.status==='needs_review','STOP_NOT_FALSE_COMPLETED');});
  await test('provider-account-is-pinned-and-same-mode-switch-cannot-resume-create-or-stop',async()=>{const i=await setup(),f=provider(),req=request(i.projectId);f.fail('price');await run(req,f.ext);await expireLease(i.projectId);f.ext.accountId=async()=>'acct_otherfixture';check((await run(req,f.ext)).result==='needs_review'&&f.prices.size===1&&f.keys.size===0,'OTHER_ACCOUNT_NO_CREATE');const a=await db.from('natori_payment_link_attempts').select('provider_account_id').eq('project_id',i.projectId).single();check(a.data?.provider_account_id==='acct_phase2cfixture','SOURCE_PINNED');check((await db.from('natori_payment_link_attempts').update({provider_account_id:'acct_otherfixture'}).eq('project_id',i.projectId)).error,'ACCOUNT_PIN_IMMUTABLE');const active=await setup(),g=provider();await run(request(active.projectId),g.ext);const v=await view(active.projectId),link=links.get(v.url!.split('/').at(-1)!)!;g.ext.accountId=async()=>'acct_otherfixture';await expireCreation(active.projectId);await stopDuePaymentLinks(g.ext);check(link.active&&(await view(active.projectId)).state==='needs_review','ACCOUNT_SWITCH_NO_FALSE_STOP');});
  await test('owner-and-anonymous-boundaries-remain-private',async()=>{const i=await setup(),wrong=randomUUID();check((await peer.rpc('natori_payment_links_v1',{p_owner_id:wrong,p_project_id:i.projectId,p_command:'read'})).data?.result==='not_found','OWNER');const anon=createClient(origin,keys.anon,{auth:{persistSession:false}});check((await anon.rpc('natori_payment_links_v1',{p_owner_id:owner,p_project_id:i.projectId,p_command:'read'})).error,'ANON_RPC');});
  writeFileSync('/results/phase2c-integration.json',JSON.stringify({tests:results,passed:results.filter(t=>t.status==='passed').length,failed:results.filter(t=>t.status==='failed').length,skipped:0,provider:'injected synthetic provider transport only; real Stripe test mode pending'},null,2));
  check(results.length===33&&results.every(t=>t.status==='passed'),'REQUIRED_TESTS_FAILED');console.log('PHASE 2C DB 33 passed / 0 failed / 0 skipped; actual Stripe pending');
 }finally{globalThis.fetch=direct;}
}
main().catch(()=>{console.error('Phase2C integration failed; raw payloads and credentials withheld');process.exitCode=1;});
