import {createClient} from '@supabase/supabase-js';
import {readFileSync,writeFileSync} from 'node:fs';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import Stripe from 'stripe';
import {NextRequest} from 'next/server';
const check=(v:unknown,c:string)=>{if(!v)throw new Error(c);};
const results:{name:string;status:string;code?:string}[]=[];
async function test(name:string,fn:()=>Promise<void>){try{await fn();results.push({name,status:'passed'});console.log(`PASS phase2b/${name}`);}catch(e){const code=e instanceof Error&&/^[A-Z_0-9]+$/.test(e.message)?e.message:'ASSERTION_FAILED';results.push({name,status:'failed',code});console.log(`FAIL phase2b/${name} ${code}`);}}
async function main(){
 const {origin}=JSON.parse(readFileSync('/runtime/network.json','utf8'));check(/^http:\/\/172\.30\.250\.\d+:8000$/.test(origin),'DESTINATION_REJECTED');
 const keys=JSON.parse(readFileSync('/runtime/credentials.json','utf8'));
 const db=createClient(origin,keys.service,{auth:{persistSession:false}}),peer=createClient(origin,keys.service,{auth:{persistSession:false}});
 const direct=globalThis.fetch;let fault:'claim'|'complete'|null=null,blocked=0;
 globalThis.fetch=async(input,init)=>{const u=new URL(typeof input==='string'?input:input instanceof URL?input.href:input.url);if(u.origin!==origin){blocked++;throw new Error('DESTINATION_REJECTED');}
  if(fault==='claim'&&u.pathname.endsWith('/rpc/natori_stripe_event_claim_v1')){fault=null;return new Response('{}',{status:503});}
  const response=await direct(input,init);if(fault==='complete'&&u.pathname.endsWith('/rpc/natori_stripe_event_complete_v1')){fault=null;check(response.ok,'COMMITTED');return new Response('{}',{status:503});}return response;};
 try{
  const auth=await db.auth.admin.createUser({email:'owner@phase2b.invalid',password:randomBytes(32).toString('hex'),email_confirm:true});check(auth.data.user,'AUTH_FIXTURE');const owner=auth.data.user!.id;
  const signingSecret='whsec_'+randomBytes(32).toString('hex');
  Object.assign(process.env,{NEXT_PUBLIC_SUPABASE_URL:origin,NEXT_PUBLIC_SUPABASE_ANON_KEY:keys.anon,SUPABASE_SERVICE_ROLE_KEY:keys.service,
   STRIPE_SECRET_KEY:'sk_test_'+randomBytes(32).toString('hex'),STRIPE_WEBHOOK_SECRET:signingSecret,
   NATORI_OWNER_USER_ID:owner,NATORI_PAYMENT_INTEGRITY_ENABLED:'1',NATORI_STRIPE_MODE:'test',
   NATORI_ACCEPTANCE_OUTBOX_ENABLED:'1',NATORI_NOTIFICATION_SENDING_ENABLED:'0',RESEND_API_KEY:'',ADMIN_API_TOKEN:''});
  const route=await import('../../src/app/api/webhook/stripe/route');
  const {normalizeNatoriPaymentEvent}=await import('../../src/features/natori/lib/paymentEvent');
  const stripe=new Stripe(process.env.STRIPE_SECRET_KEY!);
  async function setup(){const p=await db.from('natori_projects').insert({user_id:owner,title:'Payment fixture',client_name:'Synthetic',client_email:'client@phase2b.invalid',type:'illustration',status:'inquiry',amount:12000,quoted_amount:12000}).select('id').single();check(!p.error&&p.data,'PROJECT');
   const q=await db.from('natori_quotes').insert({project_id:p.data!.id,user_id:owner,version:1,title:'Payment fixture',client_name:'Synthetic',to_email:'client@phase2b.invalid',amount:12000,subject:'Quote',body_snapshot:'Body',token_hash:createHash('sha256').update(randomUUID()).digest('hex'),expires_at:new Date(Date.now()+86400000).toISOString(),accepted_at:new Date().toISOString()}).select('id').single();check(!q.error&&q.data,'QUOTE');
   check(!(await db.from('natori_projects').update({status:'awaiting_payment',payment_quote_id:q.data!.id,active_quote_id:q.data!.id,quote_accepted_at:new Date().toISOString(),quote_accepted_amount:12000}).eq('id',p.data!.id)).error,'PAYMENT_QUOTE');
   return {projectId:p.data!.id,quoteId:q.data!.id,sessionId:'cs_test_'+randomUUID().replaceAll('-','')};}
  type Input=Awaited<ReturnType<typeof setup>>;
  function event(input:Input,options:{id?:string;amount?:number;currency?:string;quoteId?:string;live?:boolean}={}):Stripe.Event{return {id:options.id??'evt_'+randomUUID().replaceAll('-',''),object:'event',type:'checkout.session.completed',livemode:options.live??false,created:Math.floor(Date.now()/1000),data:{object:{id:input.sessionId,object:'checkout.session',payment_status:'paid',status:'complete',amount_total:options.amount??12000,currency:options.currency??'jpy',payment_intent:'pi_test_'+randomUUID().replaceAll('-',''),metadata:{kind:'natori_commission',projectId:input.projectId,quoteId:options.quoteId??input.quoteId}}}} as unknown as Stripe.Event;}
  async function post(e:Stripe.Event,bad=false){const payload=JSON.stringify(e),signature=bad?'invalid':stripe.webhooks.generateTestHeaderString({payload,secret:signingSecret});return route.POST(new NextRequest('http://localhost/api/webhook/stripe',{method:'POST',body:payload,headers:{'stripe-signature':signature}}));}
  async function transactions(id:string){return (await db.from('natori_payment_transactions').select('*').eq('project_id',id)).data??[];}
  async function notices(id:string){return (await db.from('natori_notification_jobs').select('id,status,purpose').eq('project_id',id)).data??[];}
  async function claim(e:Stripe.Event,token:string){const normalized=normalizeNatoriPaymentEvent(e);return db.rpc('natori_stripe_event_claim_v1',{p_owner_id:owner,p_account:normalized.account,p_live:e.livemode,p_event_id:e.id,p_type:e.type,p_request:normalized.request,p_claim_token:token});}
  async function complete(e:Stripe.Event,token:string,generation:number,ownerId=owner){return peer.rpc('natori_stripe_event_complete_v1',{p_owner_id:ownerId,p_account:'platform',p_live:e.livemode,p_event_id:e.id,p_claim_token:token,p_generation:generation});}
  await test('signed-sdk-event-records-payment-inbox-and-two-notices-atomically',async()=>{const i=await setup(),e=event(i);check((await post(e)).status===200,'ACK');const p=await db.from('natori_projects').select('status,paid_amount,payment_confirmed_at').eq('id',i.projectId).single();check(p.data?.status==='rough'&&p.data.paid_amount===12000&&p.data.payment_confirmed_at,'PAID');check((await transactions(i.projectId)).length===1&&(await notices(i.projectId)).length===2,'ATOMIC_EFFECTS');check((await db.from('natori_stripe_event_inbox').select('status').eq('event_id',e.id).single()).data?.status==='completed','COMPLETED');});
  await test('concurrent-same-event-has-one-money-effect',async()=>{const i=await setup(),e=event(i),responses=await Promise.all([post(e),post(e)]);check(responses.every(r=>[200,503].includes(r.status))&&responses.some(r=>r.status===200),'CONCURRENT_ACK');check((await transactions(i.projectId)).length===1&&(await notices(i.projectId)).length===2,'ONE_EFFECT');});
  await test('different-event-same-session-reuses-money-and-notice',async()=>{const i=await setup(),e=event(i);check((await post(e)).status===200,'FIRST');check((await post({...e,id:'evt_'+randomUUID()})).status===200,'SECOND');check((await transactions(i.projectId)).length===1&&(await notices(i.projectId)).length===2,'SESSION_DEDUP');});
  await test('interrupted-claim-non2xx-then-expired-lease-is-recovered',async()=>{const i=await setup(),e=event(i),token=randomUUID();check((await claim(e,token)).data?.[0]?.result==='claimed','CLAIM');check((await post(e)).status===503,'UNFINISHED_NOT_ACKED');check((await transactions(i.projectId)).length===0,'NO_EFFECT');await db.from('natori_stripe_event_inbox').update({lease_until:new Date(Date.now()-1000).toISOString()}).eq('event_id',e.id);check((await post(e)).status===200,'RECOVERED');check((await transactions(i.projectId)).length===1,'ONE_PAYMENT');});
  await test('expired-worker-is-fenced-after-new-claim',async()=>{const i=await setup(),e=event(i),a=randomUUID(),b=randomUUID();const first=await claim(e,a);await db.from('natori_stripe_event_inbox').update({lease_until:new Date(Date.now()-1000).toISOString()}).eq('event_id',e.id);const second=await claim(e,b);check((await complete(e,a,first.data![0].generation)).data?.[0]?.result==='stale','STALE');check((await transactions(i.projectId)).length===0,'STALE_NO_EFFECT');check((await complete(e,b,second.data![0].generation)).data?.[0]?.result==='completed','NEW_COMPLETES');});
  await test('commit-response-loss-and-ack-loss-replay-without-new-effect',async()=>{const i=await setup(),e=event(i);fault='complete';check((await post(e)).status===503,'RESPONSE_LOST');const before=(await transactions(i.projectId))[0];check(before,'COMMITTED');check((await post(e)).status===200&&(await post(e)).status===200,'REPLAY');const after=await transactions(i.projectId);check(after.length===1&&after[0].received_at===before.received_at&&(await notices(i.projectId)).length===2,'IMMUTABLE_EFFECT');});
  await test('db-claim-failure-remains-retryable',async()=>{const i=await setup(),e=event(i);fault='claim';check((await post(e)).status===503,'DB_FAILURE');check((await post(e)).status===200&&(await transactions(i.projectId)).length===1,'RETRY');});
  await test('legacy-shared-event-with-no-payment-is-not-permanently-ignored',async()=>{const i=await setup(),e=event(i);await db.from('processed_stripe_events').insert({event_id:e.id});check((await post(e)).status===200&&(await transactions(i.projectId)).length===1,'LEGACY_RECOVERED');check((await db.from('processed_stripe_events').select('event_id').eq('event_id',e.id)).data?.length===1,'LEGACY_UNTOUCHED');});
  await test('legacy-recorded-session-does-not-replay-unknown-old-mail',async()=>{const i=await setup(),e=event(i),when=new Date().toISOString();await db.from('natori_payment_transactions').insert({project_id:i.projectId,quote_id:i.quoteId,stripe_session_id:i.sessionId,amount:12000,status:'received',received_at:when});await db.from('natori_projects').update({payment_confirmed_at:when,stripe_payment_session_id:i.sessionId,paid_amount:12000,status:'rough'}).eq('id',i.projectId);check((await post(e)).status===200&&(await transactions(i.projectId)).length===1&&(await notices(i.projectId)).length===0,'LEGACY_FACT_ONLY');});
  await test('amount-mismatch-is-durable-review-not-confirmed-payment',async()=>{const i=await setup(),e=event(i,{amount:5000});check((await post(e)).status===200,'REVIEW_ACK');check((await transactions(i.projectId))[0]?.status==='amount_mismatch','REVIEW_LEDGER');check((await db.from('natori_projects').select('payment_confirmed_at').eq('id',i.projectId).single()).data?.payment_confirmed_at===null,'NOT_PAID');check((await db.from('natori_stripe_event_inbox').select('status').eq('event_id',e.id).single()).data?.status==='needs_review','REVIEW');});
  await test('unrelated-quote-and-currency-do-not-confirm-payment',async()=>{const other=await setup();for(const options of [{quoteId:other.quoteId},{currency:'usd'}]){const i=await setup(),e=event(i,options);check((await post(e)).status===200&&(await transactions(i.projectId)).length===0,'REVIEW_ONLY');check((await db.from('natori_stripe_event_inbox').select('status').eq('event_id',e.id).single()).data?.status==='needs_review','REVIEW');}});
  await test('second-session-is-recorded-as-duplicate-without-replacing-paid-facts',async()=>{const i=await setup();check((await post(event(i))).status===200,'FIRST');const before=await db.from('natori_projects').select('paid_amount,payment_confirmed_at,stripe_payment_session_id').eq('id',i.projectId).single();check((await post(event({...i,sessionId:'cs_test_'+randomUUID()}))).status===200,'SECOND');const after=await db.from('natori_projects').select('paid_amount,payment_confirmed_at,stripe_payment_session_id').eq('id',i.projectId).single();check(JSON.stringify(before.data)===JSON.stringify(after.data)&&(await transactions(i.projectId)).some(t=>t.status==='duplicate_payment'),'FACTS_PRESERVED');});
  await test('closed-and-archived-delayed-payments-do-not-reopen-work',async()=>{for(const archived of [false,true]){const i=await setup(),e=event(i);await db.from('natori_projects').update(archived?{deleted_at:new Date().toISOString(),next_action:'Keep terminal'}:{status:'closed',next_action:'Keep terminal'}).eq('id',i.projectId);check((await post(e)).status===200,'ACK');const p=await db.from('natori_projects').select('status,next_action,payment_confirmed_at').eq('id',i.projectId).single();check(p.data?.status===(archived?'awaiting_payment':'closed')&&p.data.next_action==='Keep terminal'&&p.data.payment_confirmed_at,'TERMINAL_PRESERVED');}});
  await test('mail-configuration-failure-never-rolls-back-payment',async()=>{const i=await setup(),e=event(i);process.env.NATORI_NOTIFICATION_SENDING_ENABLED='1';try{check((await post(e)).status===200,'ACK');check((await transactions(i.projectId)).length===1,'PAYMENT_DURABLE');const jobs=await notices(i.projectId);check(jobs.length===2&&jobs.every(j=>j.status==='failed'),'MAIL_SEPARATE');}finally{process.env.NATORI_NOTIFICATION_SENDING_ENABLED='0';}});
  await test('signature-mode-and-direct-anonymous-rpc-are-denied',async()=>{const i=await setup(),e=event(i);check((await post(e,true)).status===400,'SIGNATURE');check((await post({...e,livemode:true})).status===503,'MODE');const anon=createClient(origin,keys.anon,{auth:{persistSession:false}});check((await anon.rpc('natori_stripe_event_complete_v1',{p_owner_id:owner,p_account:'platform',p_live:false,p_event_id:e.id,p_claim_token:randomUUID(),p_generation:1})).error,'ANON_RPC');check((await transactions(i.projectId)).length===0,'NO_EFFECT');});
  writeFileSync('/results/phase2b-integration.json',JSON.stringify({tests:results,passed:results.filter(t=>t.status==='passed').length,failed:results.filter(t=>t.status==='failed').length,skipped:0,provider:'synthetic Stripe SDK signed payloads only; no real Stripe test-mode delivery',blockedDestinations:blocked},null,2));
  check(results.length===15&&results.every(t=>t.status==='passed'),'REQUIRED_TESTS_FAILED');console.log('PHASE 2B 15 passed / 0 failed / 0 skipped; actual Stripe pending');
 }finally{globalThis.fetch=direct;}
}
main().catch(()=>{console.error('Phase2B integration failed; raw payloads and credentials withheld');process.exitCode=1;});
